import type { CombatStyle } from "../../types";

export const BARTITSU: CombatStyle = {
  name: "Bartitsu",
  origin: "England (London)",
  era: "Developed by E.W. Barton-Wright circa 1898–1902; the first synthesis of Asian and European martial arts; achieved fictional immortality when Arthur Conan Doyle attributed its use to Sherlock Holmes.",
  corePhilosophy: "Barton-Wright described Bartitsu as 'the new art of self-defence.' Its philosophy was pragmatic eclecticism: take the most effective elements from judo (throws and joint locks), savate (French kickboxing), boxing (punching), and la canne (walking stick fighting), and combine them into a system suited for a Victorian gentleman faced with street attack. The walking stick is the system's primary weapon — an item carried by every respectable person of the era, not recognizable as a weapon until it is used as one.",
  bodyMechanics: "The BNR dataset on cane/stick combat mechanics establishes that a walking stick of 90cm–1m length operated with two-hand grips can generate blocking forces that stop most unarmed strikes without injury to the defender. The primary mechanical insight of la canne technique — which Bartitsu incorporated — is that the stick is a fulcrum, not a club: the end not striking is the control point, and most blocks and trips work by levering the stick against the opponent's limb rather than striking directly. The judo component contributes kuzushi (balance-breaking) and hip throws that work from the lapel grips natural to Victorian clothing.",
  distancePreference: "Mid-range with the walking stick as the reach extender; close range for the judo and boxing components.",
  footworkPrinciple: "Upright and mobile — the footwork of a gentleman who is technically 'not in a fighting stance.' The evasion is lateral rather than backward, placing the practitioner beside the attack rather than away from it.",
  stances: [
    { name: "Gentleman's Guard", bodyPosition: "Walking stick held in both hands, body upright with minimal visible fighting posture, feet in a natural walking position.", weightDistribution: "50% front / 50% rear", strengths: "Does not communicate combative intent. The stick is already in both hands. The upright posture is consistent with Victorian social norms.", weaknesses: "The neutral appearance requires the practitioner to act first without an obvious defensive position." },
    { name: "Cane Fighting Guard", bodyPosition: "Stick forward, one end toward the opponent as a measure of distance, back hand ready to drive the near end, body sideways to minimize target area.", weightDistribution: "55% rear / 45% front", strengths: "Maximum stick reach. Both ends of the stick can attack or block. The sideways profile is harder to strike.", weaknesses: "Communicates combative intent, losing the tactical advantage of surprise." },
  ],
  strikes: [
    { name: "Cane Trip (Crook Hook)", mechanics: "The hooked end of the walking stick catches the opponent's ankle or calf and pulls backward, unloading their weight from that leg. The BNR data on leg trips shows the critical element is timing — the trip must coincide with the opponent's weight loading onto the targeted leg, not when the leg is in the air.", setup: "The opponent is advancing and their weight is forward.", execution: "The crook of the stick hooks the ankle or calf mid-step, the near hand drives the stick handle forward to lever the leg backward, and the opponent's forward momentum carries them down.", recovery: "Step back from the falling opponent immediately.", counter: "Step over the sweeping stick." },
    { name: "Boxing Combination (from Bartitsu)", mechanics: "Victorian boxing differed from modern boxing in its upright stance and longer-range lead-hand emphasis. The lead hand was extended further than modern boxing, and the cross was delivered with a straighter, less rotating motion. The combination is jab (measure distance) to cross (power strike) to clinch entry (judo grip).", setup: "The opponent is at punching range.", execution: "Lead hand extends to the opponent's face (jab), cross follows with hip rotation, the clinch entry converts the cross's forward momentum into a judo-style grip.", recovery: "Either complete the throw or disengage from the clinch if the throw is defended.", counter: "Slip outside the jab and fire before the cross arrives." },
  ],
  defenses: [
    { name: "Lateral Evasion", mechanics: "A step to the side of the incoming attack — specifically stepping offline so the attack passes in front of rather than into the practitioner. The lateral evasion is combined with a simultaneous counter: as the attack passes by, the practitioner's near hand strikes or grabs.", setup: "A strike or attack is incoming.", execution: "The step is lateral and forward — not backward — placing the practitioner beside the attacker rather than retreating from them. The counter fires simultaneously.", recovery: "Immediate follow-up from the new flanking position.", counter: "A combination where the second strike redirects to match the lateral step." },
  ],
  strengthAgainst: ["Untrained attackers who rely on the haymaker — the cane trip and lateral evasion were specifically developed for street attack scenarios.", "Multiple attackers in formation — the stick extends the threat envelope and keeps attackers at distance.", "Close-range grappling attempts — the judo component handles transitions that pure boxing would not."],
  weakAgainst: ["Modern combat sports practitioners who train specifically for the ranges that Bartitsu overlaps.", "Weapon attacks — the system assumes an unarmed attacker or one with a club.", "Any sustained ground exchange — the system does not include a ground fighting component."],
  signatureTells: ["The walking stick is always in hand or very close to hand.", "The lateral footwork habit shows in non-combative movement — Bartitsu practitioners tend to step sideways when approached unexpectedly.", "The grip shifts on the stick before any defensive action — both hands coming to active positions."],
  pacing: "Bartitsu has the pacing of Victorian social confrontation — restrained and formal until the moment it isn't. An encounter with a Bartitsu practitioner escalates from polite discomfort to decisive physical action very quickly, without the extended sparring phase of sport martial arts.",
  writingNotes: "A Bartitsu practitioner is defined by the combination of social propriety and genuine lethality that Victorian England was designed to conceal. They are courteous, controlled, and lethal when pushed — and they were trained specifically for the situations where polite society intersects with danger.",
};
