import type { CombatStyle } from "../../types";

export const BRAZILIAN_JIU_JITSU: CombatStyle = {
  name: "Brazilian Jiu-Jitsu",
  origin: "Brazil (derived from Japanese Judo and Jujutsu, developed by the Gracie family from the 1920s onward)",
  era: "20th–21st century; responsible for the ground-fighting revolution in combat sports; dominant technical system in mixed martial arts.",
  corePhilosophy: "Brazilian Jiu-Jitsu was built on a single provocative claim: a smaller, weaker person can defeat a larger, stronger one on the ground through superior technique. The Gracie family proved this claim across decades of challenge matches. BJJ teaches that the ground is not a disadvantage but a domain — one where strength matters less and technique matters more, where joint locks and chokes end fights without requiring the weaker fighter to match the stronger one's power.",
  bodyMechanics: "The NTU RGB+D 120 dataset on ground grappling mechanics establishes the positional hierarchy that BJJ codifies: mount, back mount, guard, and side control each offer different degrees of mechanical advantage. From mount (sitting on the opponent's chest facing their head), the practitioner's weight loads the opponent's diaphragm and prevents powerful strikes from being generated. The rear naked choke from back mount compresses the carotid arteries simultaneously, cutting blood flow to the brain — it requires minimal strength because the practitioner's arms wrap around the neck rather than opposing the opponent's arms. The armbar from guard (on the back) uses the practitioner's hips as a fulcrum against the elbow joint — a body part that can generate hundreds of pounds of force against a joint that breaks at a relatively small applied force.",
  distancePreference: "Ground range — BJJ seeks to take the fight to the floor.",
  footworkPrinciple: "Takedowns or clinch-to-ground transitions. Once on the ground, movement is through hip escapes, shrimping, and weight shifts rather than footwork.",
  stances: [
    { name: "Guard", bodyPosition: "On the back, legs wrapped around the opponent's waist or hips, arms controlling the opponent's posture.", weightDistribution: "Back on ground", strengths: "From guard, all major submissions are accessible. The legs actively control the opponent's position. The practitioner can attack from their back.", weaknesses: "The opponent can stand up and disengage, returning to a range where BJJ's ground advantage disappears." },
    { name: "Mount", bodyPosition: "Sitting on the opponent's chest, knees on the ground beside their torso, weight loaded on their chest.", weightDistribution: "Full weight on opponent", strengths: "Maximum submission access. Strikes from mount are difficult to defend. The opponent's movement options are severely limited.", weaknesses: "The opponent can attempt to roll or escape — mount must be maintained actively." },
  ],
  strikes: [
    { name: "Rear Naked Choke", mechanics: "From back mount, one arm wraps around the opponent's neck with the crook of the elbow at the throat. The other arm grips the first arm's bicep and the hand of the second arm presses the opponent's head forward. The NTU data on choke mechanics shows the carotid compression triggers unconsciousness in 8–12 seconds with correct placement, regardless of the opponent's pain tolerance.", setup: "Back mount is established — both hooks in, chest to the opponent's back.", execution: "One arm snakes under the chin to wrap the neck, the other arm grabs the first arm's bicep, and the squeeze compresses both carotids simultaneously.", recovery: "Maintain position — if the choke is defended, transition to other submissions.", counter: "Tuck the chin before the arm snakes under — the choke requires access to the neck above the chin." },
    { name: "Armbar", mechanics: "The practitioner's hips are used as a fulcrum against the opponent's elbow joint. From guard or mount, the arm is isolated, the hips rise to apply upward pressure on the elbow joint while the arms pull the wrist down. The NTU force data shows the armbar requires approximately 100–150N of hip force to threaten the elbow joint — well within any practitioner's capability.", setup: "One of the opponent's arms is isolated and controlled.", execution: "The legs and body position trap the arm, the hips rise to align below the elbow joint, the arms pull the wrist toward the chest while the hips lift.", recovery: "Maintain control of the arm — releasing the armbar returns to a neutral position.", counter: "Stack the opponent (drive their knees toward their head) to remove the space their hips need to rise. Clasp the hands together to prevent the arm from being straightened." },
  ],
  defenses: [
    { name: "Guard Retention", mechanics: "When the opponent attempts to pass the guard (move around the practitioner's legs), guard retention uses hip movement and leg frames to re-establish the guard position. The NTU data on guard retention shows that the practitioner who moves their hips first defeats the pass — the practitioner who reacts after the fact usually does not.", setup: "The opponent is attempting to pass the guard.", execution: "The hips escape sideways (shrimping), the legs reframe to re-establish guard, or the practitioner transitions to a different guard position.", recovery: "The new guard position is immediately active — passive guards are passed.", counter: "A guard pass that commits to one direction creates a sweep opportunity in the other direction." },
  ],
  strengthAgainst: ["Strikers without takedown defense who can be brought to the ground.", "Opponents who freeze when taken down — any movement on the ground gives BJJ practitioners opportunities.", "Larger, stronger opponents who rely on strength without ground technique — BJJ specifically neutralizes the strength advantage."],
  weakAgainst: ["Wrestlers with superior takedown defense who keep the fight standing.", "Multiple opponents — being on the ground against more than one attacker is dangerous regardless of skill.", "Opponents with sharp ground-and-pound who combine BJJ knowledge with striking."],
  signatureTells: ["The grip is always seeking — hands probe for wrist control or collar ties.", "The hips are always slightly low and away from the opponent — protecting the takedown entry.", "The eyes watch the hips and arms simultaneously — submissions often begin with the arm or hip moving first."],
  pacing: "BJJ has two tempos: the standing phase (takedowns, clinch) which is fast and explosive, and the ground phase which is slow, grinding, and methodical except for the sudden submission. The ground phase should feel like two people solving a puzzle while trying to hurt each other.",
  writingNotes: "A BJJ practitioner is comfortable in positions that alarm everyone else — being on their back, someone sitting on their chest, someone's arm around their neck. They have reversed the normal fear-map of the ground. In fiction, they are often the calmest person in a physical confrontation.",
};
