import type { CombatStyle } from "../../types";

export const CAPOEIRA: CombatStyle = {
  name: "Capoeira",
  origin: "Brazil (developed by enslaved Africans from the 16th century onward)",
  era: "16th–21st century; suppressed and criminalized throughout much of its history; experienced a major global revival in the late 20th century.",
  corePhilosophy: "Capoeira was created by people who were not allowed to train fighting arts openly. It disguised itself as dance, the attacks as acrobatics, the sparring as music and performance. This history is not decorative context — it is the art's core logic. Everything in Capoeira is ambiguous. A movement that looks like a cartwheel is also a kick. A handstand is also a weapon. A retreat is also an attack. The ginga (the rocking movement that is the art's foundation) is simultaneously a guard, a feint, a footwork system, and a signal of readiness. The art is built on the principle that your attacker should never be certain what you are doing.",
  bodyMechanics: "The ginga (the constant rocking side-to-side motion) keeps the body in motion, making it a continuously moving target while generating the kinetic energy that feeds the kicks. The BNR data on continuous-motion striking shows that a body already in motion generates kicks faster than a stationary body — the ginga pre-loads the rotation. The primary kicks are circular — the meia-lua (half-moon) sweeps in a wide arc from the side, the queixada (jawbreaker) comes from the outside inward. The circular mechanics mean these kicks can be modified mid-flight if the target moves. The baixo (low game) inverts the body — handstands, cartwheels, and rolls — dropping below the opponent's strike line while attacking from angles they are not prepared to defend.",
  distancePreference: "Mid-range with constant distance variation through the ginga.",
  footworkPrinciple: "The ginga is the footwork — a constant side-to-side rocking that is never still. The practitioner flows between the ginga and the specific entries for each attack without discrete transitions.",
  stances: [
    { name: "Ginga", bodyPosition: "Feet constantly shifting side to side in a wide stance, torso rocking, one arm protecting the face at all times, weight flowing from foot to foot in a rhythmic pattern.", weightDistribution: "Always shifting — no fixed distribution", strengths: "A continuously moving target is harder to hit than a stationary one. The ginga generates energy that feeds the kicks. The motion is hypnotic and masks the attack's timing.", weaknesses: "The rhythm of the ginga can be timed by a patient opponent. The wide stance is vulnerable to leg sweeps." },
  ],
  strikes: [
    { name: "Meia-Lua de Frente (Half-Moon Front)", mechanics: "A horizontal leg swing in a semicircular arc toward the opponent's head or torso. The kick begins from the ginga's weight transfer and flows into the horizontal arc without a visible preparation phase.", setup: "The ginga is in progress and the opponent's head is accessible.", execution: "From the ginga's side step, the swinging leg rises and sweeps in a horizontal arc toward the target. The opposite arm counterbalances.", recovery: "The leg continues its arc and returns to the ginga's rhythm.", counter: "Step inside the arc — the meia-lua cannot track inward once committed." },
    { name: "Rasteira (Leg Sweep)", mechanics: "A low, sweeping hook of the opponent's supporting leg while in the baixo (low game). The sweep is delivered from a partially inverted position — the hand or foot hooks the opponent's ankle or calf while the practitioner is on their hands or in a crouch.", setup: "The practitioner is in the baixo and the opponent's weight is on the target leg.", execution: "From the low position, the sweeping leg hooks the opponent's ankle, pulling it forward while the hip drives in the opposite direction.", recovery: "Rise immediately from the baixo position or transition to another low attack.", counter: "Transfer weight to the other leg immediately, or hop over the sweep." },
  ],
  defenses: [
    { name: "Au (Cartwheel Evasion)", mechanics: "A cartwheel performed at the moment an attack arrives, carrying the body out of the attack's path while arriving in a new position. The au is simultaneously evasion and repositioning — the practitioner who cartwheels away from an attack can kick from the handstand position mid-cartwheel.", setup: "An attack is incoming.", execution: "The au carries the body sideways out of the attack line, the arms absorb the landing, the feet arrive in position for the next attack.", recovery: "Return to the ginga rhythm from the au's landing position.", counter: "Pursue the direction the au is traveling — the au has a committed path that can be anticipated." },
  ],
  strengthAgainst: ["Opponents who expect linear attacks and cannot track circular kicks.", "Fighters who commit to single attacks — the ginga's ambiguity makes timing extremely difficult.", "Anyone who tries to read the attack line — Capoeira's circular mechanics make the final angle impossible to predict from the setup."],
  weakAgainst: ["Grapplers who close distance and take the Capoeirista to the ground — the art does not function in sustained clinch.", "Fighters in confined spaces where the ginga cannot operate.", "Opponents who control the distance and deny the mid-range where the circular kicks operate."],
  signatureTells: ["The ginga never stops — a Capoeirista who is stationary is recovering, not resting.", "The eyes are rarely directly on the target — peripheral vision is emphasized, which means the gaze drifts.", "Before the baixo (low game), the hips drop slightly and the hands come toward the floor."],
  pacing: "Capoeira has the most variable pacing of any martial art — in the jogo (the game), the pace is set by the music's rhythm and both practitioners' willingness to engage or retreat. In a real fight, the art operates at the speed of the kicks: explosive, circular, then back to the ginga. It should never look stationary.",
  writingNotes: "A Capoeirista carries the art's concealment in their personality — they rarely show their full hand. They tend toward ambiguity, misdirection, and the performance of something other than what they are actually doing. In fiction, they are the most dangerous when they seem to be at ease.",
};
