import type { CombatStyle } from "../../types";

export const KRAV_MAGA: CombatStyle = {
  name: "Krav Maga",
  origin: "Israel (developed for the Israel Defense Forces)",
  era: "20th century; developed by Imi Lichtenfeld in the 1940s–50s; continuously updated based on real-world combat and law enforcement experience.",
  corePhilosophy: "Krav Maga has one purpose: survival. There are no competitions, no forms, no philosophy beyond getting home alive. The system is built on three principles: counter-attack simultaneously with defense, target vulnerable anatomy, and finish the threat completely. It assumes the worst-case scenario — multiple attackers, weapons, confined spaces — and teaches the simplest possible solution to each. Its practitioners are not martial artists. They are people trained to hurt someone enough to escape.",
  bodyMechanics: "Krav Maga deliberately avoids biomechanical complexity. Techniques are selected for their function under stress-induced fine-motor degradation — simple gross-motor movements that work when adrenaline is flooding the system. The simultaneous defense-and-counter is the system's core mechanical insight: blocking and striking are not separate sequential actions. The forearm deflects the incoming strike while the opposite hand is already striking the attacker's face. The BIO literature on simultaneous action under stress confirms this is effective — it compresses reaction time and prevents the attacker from recovering between a block and a counter.",
  distancePreference: "Any range — Krav Maga has responses for all distances, including weapon situations. The preferred outcome is immediate close-range damage and escape.",
  footworkPrinciple: "The 360-degree burst — a diagonal step off the attack line that simultaneously removes the practitioner from harm's way and creates a flanking attack angle. The step is always at 45 degrees to the incoming attack, never straight back.",
  stances: [
    { name: "Passive Stance", bodyPosition: "Hands open at chest height, neutral appearance, weight slightly forward, ready to burst.", weightDistribution: "50% front / 50% rear", strengths: "Does not telegraph defensive training. The hands are in position to parry without looking like they are. The neutral appearance does not escalate verbal confrontations.", weaknesses: "Less structurally strong than a fighting stance. The neutral appearance requires the practitioner to act first without obvious defensive posture." },
    { name: "Fighting Stance", bodyPosition: "Hands raised, chin down, dominant foot back, weight distributed for mobility.", weightDistribution: "55% rear / 45% front", strengths: "Hands protect the face. Weight distribution allows immediate forward burst.", weaknesses: "Communicates fighting intent — may escalate when de-escalation was possible." },
  ],
  strikes: [
    { name: "360-Degree Defense and Counter", mechanics: "The forearm intercepts an incoming strike from any of the eight primary angles (the 360 system) while the opposite hand simultaneously strikes the attacker's face. The defense and counter are a single motion, not sequential actions. The BIO data on simultaneous action confirms the attacker has no recovery window between defense and counter.", setup: "Any incoming attack — the system trains responses to all eight attack angles.", execution: "The forearm of the near arm rises to intercept at 45 degrees (redirecting rather than blocking), while the opposite hand drives a palm strike or straight punch to the attacker's face.", recovery: "Continue attacking — Krav Maga does not stop after the first counter.", counter: "Against a trained Krav practitioner, the 360-degree defense expects a single attack line. Attack from two simultaneous lines to overwhelm the simultaneous-response system." },
    { name: "Groin Kick", mechanics: "A fast, direct kick to the groin using the instep or knee. Selected because the anatomical target is always accessible, requires minimal technical precision, and creates immediate incapacitation regardless of the attacker's pain tolerance.", setup: "The attacker is at kicking range.", execution: "The knee drives forward and up from a burst step, the foot or knee contacts the groin.", recovery: "Immediately attack the secondary target (face, eyes, or throat) while the attacker is reacting.", counter: "Protect the groin by lowering the hips and turning sideways — the Krav practitioner will immediately target the new accessible anatomy." },
    { name: "Eye Strike", mechanics: "A direct strike to the eyes using fingertips or thumb. Selected because it bypasses all conditioning — there is no way to condition the eyes against a direct strike — and creates immediate threat neutralization.", setup: "Any range where the hand can reach the attacker's face.", execution: "The fingers drive directly at the eyes. No telegraphing, no wind-up.", recovery: "Immediately exploit the attacker's protective reaction — they will cover their eyes, exposing other targets.", counter: "A practitioner who telegraphs the eye strike (by looking at the target) gives the attacker time to turn their head." },
  ],
  defenses: [
    { name: "Burst Step Off-Line", mechanics: "A diagonal step at 45 degrees to the attack removes the practitioner from the attack's path while simultaneously positioning them to attack the attacker's exposed flank.", setup: "Any attack is incoming.", execution: "The step is diagonal and explosive — not a retreat, but a repositioning. The attacker's momentum carries them past.", recovery: "Immediately counter from the flanking position.", counter: "Circle to compensate for the off-line step and continue the attack." },
  ],
  strengthAgainst: ["Untrained attackers who commit to single attacks — the simultaneous defense-counter ends the exchange in the first exchange.", "Attackers in weapon situations — the system has specific disarms for common weapon attacks.", "Multiple attacker scenarios — the burst step and simultaneous system is designed for outnumbered situations."],
  weakAgainst: ["Trained combat sports athletes who do not commit to single attacks and can handle the counter.", "Sustained grappling exchanges where the system's simplicity becomes a disadvantage.", "Any situation where a solution other than immediate violence is available and better."],
  signatureTells: ["The passive stance looks neutral but the weight is already forward.", "Before any burst, the eyes scan the exit — Krav practitioners always know where they are going after.", "Hands are always at face height, even in conversation — the passive stance is a trained default.", "Attacks always aim for anatomy: eyes, throat, groin, knees — not padded areas."],
  pacing: "Krav Maga has no pacing. It explodes from apparent stillness, delivers maximum damage as fast as possible, and ends. The practitioner is gone before the attacker fully processes what happened. There is no second round if the system works correctly.",
  writingNotes: "A Krav-trained character is not a fighter. They are someone who has been trained to hurt people efficiently and without hesitation. They don't enjoy it, they don't perform it, and they don't want to be in a situation where it's necessary. When it is, they are very fast and very final.",
};
