import type { CombatStyle } from "../../types";

export const MUAY_THAI: CombatStyle = {
  name: "Muay Thai",
  origin: "Thailand",
  era: "Centuries-old Thai martial art; national sport of Thailand; the most widely used striking art in modern mixed martial arts.",
  corePhilosophy: "Muay Thai is the Art of Eight Limbs — fists, elbows, knees, and shins are all weapons of equal status. The art teaches that the body is a complete weapon at all ranges, and that the willingness to absorb damage in order to land harder counter-strikes is not recklessness but strategy. Conditioning is as important as technique: the Muay Thai fighter's shins, forearms, and body are instruments hardened through thousands of hours of contact.",
  bodyMechanics: "The roundhouse kick generates power through full hip rotation and shin impact rather than foot impact — the shin acts as a club rather than a foot sword. The hip rotation drives approximately 70% of the kick's force; the leg is essentially a bat swung from the hip. Elbow strikes at close range can cut immediately due to the bone's density and the thin skin overlying it — they are not designed to knock out but to open wounds that compromise the opponent's vision. The teep (push kick) is a range-control weapon, not a damage weapon — it works by extending through the target rather than snapping on its surface.",
  distancePreference: "Mid-range with strong clinch fighting at close range.",
  footworkPrinciple: "Grounded and forward-pressuring. Weight stays on the rear leg during kicks to allow full hip rotation. Lateral movement is less emphasized than in boxing — the art assumes ground is taken and held.",
  stances: [
    { name: "Muay Thai Guard", bodyPosition: "Hands high, chin down, elbows protecting the body, rear foot on the ball, angled stance.", weightDistribution: "55% rear / 45% front", strengths: "Protects the chin. Ready for the teep to control distance. Elbows naturally protect against body attacks.", weaknesses: "Less mobile laterally than a boxing stance. The upright torso is a target for body kicks." },
  ],
  strikes: [
    { name: "Roundhouse Kick (Dtae Wieng)", mechanics: "The hip rotates fully, the pivot foot spins out, and the shin impacts the target. Maximum force requires full hip rotation before shin contact. The kick generates power from the hip's angular velocity — the leg follows the hip, it does not lead it.", setup: "The opponent is at kicking range.", execution: "Pivot on the lead foot, rotate the hip fully, swing the shin into the target at the moment of maximum hip velocity.", recovery: "The kicking leg returns to guard immediately.", counter: "Check the kick (raise the shin to block) and counter with the opposite side." },
    { name: "Teep (Push Kick)", mechanics: "A linear front kick used to control distance, not damage. The hips drive forward behind the ball of the foot. The teep's effectiveness comes from timing — a well-timed teep stops an advancing opponent completely.", setup: "The opponent is advancing or at controlled distance.", execution: "The lead leg drives forward, the hip extends through the kick, pushing the opponent back.", recovery: "The foot returns immediately — an extended teep is a grabbed leg.", counter: "Catch the foot and sweep, or step inside before it lands." },
    { name: "Elbow Strike (Sok)", mechanics: "At close range, the elbow's dense bone strikes the opponent's head at the temple, above the eye, or on the cheekbone, cutting the skin immediately. No wind-up needed — the damage comes from proximity and hip rotation.", setup: "The clinch range — opponent is too close for punches.", execution: "The hip rotates, the elbow swings horizontally, diagonally, or downward into the target.", recovery: "Return to guard or clinch position immediately.", counter: "Clinch tightly to neutralize the rotation space needed for elbow generation." },
    { name: "Knee Strike (Ti Khao)", mechanics: "In the clinch, the knee drives upward into the midsection or drives downward onto a bent opponent. The hip drives behind the knee — a knee without hip drive loses significant force.", setup: "The clinch is established.", execution: "The clinch grip holds the opponent in position, the hip drives forward and upward, the knee rises sharply into the target.", recovery: "The foot returns to the floor and the clinch is maintained.", counter: "Sprawl backward or turn the opponent to receive the knee on the hip or thigh." },
  ],
  defenses: [
    { name: "Shin Check", mechanics: "The defending fighter raises the shin to intercept an incoming kick. Shin meets shin. The attacker's kick is stopped and may cause them pain if the defender's shin conditioning exceeds theirs.", setup: "A kick is incoming to the leg or body.", execution: "The shin rises to meet the kick, absorbing the impact along the shin bone.", recovery: "The leg returns to stance immediately.", counter: "A high kick after a series of low checks — the fighter conditioning to check low may be slow to shift." },
  ],
  strengthAgainst: ["Opponents at medium range who don't check kicks and have no answer for the shin's impact.", "Fighters without a clinch game who can be knee'd repeatedly.", "Anyone without strong shin conditioning who cannot check kicks effectively."],
  weakAgainst: ["Grapplers who take down immediately and remove the striking range.", "Boxers with superior hand speed who punish the wider stances during kick recovery.", "Fighters who check kicks effectively and counter-punch on the recovery."],
  signatureTells: ["The hip begins rotating before the kick is visible — the first tell is a weight shift to the rear leg.", "The elbow guard rises before the roundhouse — the body protecting itself before impact.", "Clinch entries always seek double underhooks — the hands probe for grip at close range.", "The shin checks are automatic — Muay Thai fighters raise their shin against body attacks reflexively."],
  pacing: "Muay Thai has a methodical, economic pace punctuated by explosive combinations. Fighters measure with the teep, establish range, then fire combinations. The clinch phase has its own grinding rhythm. The pacing should feel deliberate and heavy.",
  writingNotes: "A Muay Thai-trained character is comfortable with damage — they've been conditioned to absorb it and continue. They tend toward a quiet, hard confidence. In fiction, they're fighters who don't flinch.",
};
