import type { CombatStyle } from "../../types";

export const PANKRATION: CombatStyle = {
  name: "Pankration",
  origin: "Ancient Greece",
  era: "Introduced at the 33rd Olympic Games in 648 BCE; practiced throughout the Greek and Roman world; revived as a competitive sport in the 20th century.",
  corePhilosophy: "Pankration means 'all power.' It was the Greek synthesis of boxing (pygmachia) and wrestling (pale) into a single system with almost no rules — only eye-gouging and biting were forbidden in the Olympic version, and in the Spartan version even those were permitted. The Pankratiast was trained to fight at every range — standing, clinching, and on the ground — and to transition between them without interruption. The philosophy is completeness: no gap in the fighter's ability that an opponent can exploit.",
  bodyMechanics: "The KYO dataset's cross-range analysis shows that Pankration's historical effectiveness came from range integration — the ability to strike from wrestling clinch positions and to transition from striking exchanges into throws without reorganizing the grip. The practitioner who can punch from a wrestling clinch denies the opponent the safety of the clinch range. The NTU RGB+D 120 data on ground-and-pound mechanics shows that striking from mount or a dominant standing position over a grounded opponent generates less force than a standing punch, but the opponent's inability to evade or counter-attack compensates for the force reduction.",
  distancePreference: "All ranges — the system is designed for seamless transitions between striking and grappling distances.",
  footworkPrinciple: "Aggressive and forward. The Pankratiast does not retreat — they advance through the opponent's defenses, transitioning from striking to clinch to ground as distance changes.",
  stances: [
    { name: "Pankratiast Guard", bodyPosition: "Upright, hands forward, ready to both punch and grab, feet shoulder-width, weight balanced forward.", weightDistribution: "55% front / 45% rear", strengths: "Accessible for both punching and clinch entries. The forward weight supports both striking power and takedown driving.", weaknesses: "The upright stance is not optimized for either pure striking or pure grappling — it sacrifices some efficiency in each for versatility in both." },
  ],
  strikes: [
    { name: "Cross-Range Attack", mechanics: "A punch thrown from a wrestling clinch position or a takedown attempt initiated from a striking exchange. The KYO data on clinch-range striking shows that elbow and short hooks can be generated from a collar tie or underhook position — the opponent who is protecting against a takedown is not protecting against a punch.", setup: "The practitioner is in a clinch grip or has driven for a takedown.", execution: "From the clinch, a short elbow or hook targets the opponent's head while maintaining the grip. Alternatively, from a striking exchange, the practitioner shoots for a single or double leg.", recovery: "Maintain position — the transition from striking to grappling or back is the technique.", counter: "The hand that clinches cannot simultaneously block the strike from the other arm — prioritize breaking the grip." },
    { name: "Ground Stomp (Katakrima)", mechanics: "Over a grounded opponent, the standing practitioner stomps the face, head, or body. The historical Pankration permitted this — it is one of the techniques that made Pankration genuinely dangerous rather than competitive. Modern revived Pankration usually prohibits it, but the historical technique is relevant for fiction.", setup: "The opponent is on the ground and the practitioner is standing.", execution: "The heel drives downward into the target.", recovery: "Immediately step away from the opponent's reach.", counter: "Roll away or grab the attacking leg and take the standing fighter down." },
  ],
  defenses: [
    { name: "Shoot Counter", mechanics: "When a takedown (shoot) is incoming, the Pankratiast sprawls — driving the hips back and down, redirecting the opponent's forward momentum into the ground — and transitions immediately to a choke from the sprawl position.", setup: "A takedown attempt is incoming.", execution: "The hips drive backward and down, the weight drops onto the opponent's back, one arm wraps the neck from the top position.", recovery: "Maintain the choke or transition to back control.", counter: "A low single-leg attack targets below the sprawl's defensive position." },
  ],
  strengthAgainst: ["Single-range specialists who are competent in one domain but not transitions.", "Strikers who are not prepared to be grabbed and taken down mid-combination.", "Grapplers who are not prepared to be struck from the clinch."],
  weakAgainst: ["Modern MMA practitioners who train Pankration's range integration systematically — the modern art has refined what the ancient Greeks developed.", "Weapons — Pankration's unarmed system is not designed for weapon situations."],
  signatureTells: ["The hands are held forward — accessible for both gripping and punching.", "The level changes constantly — the Pankratiast drops and rises to test takedown and strike opportunities.", "Striking combinations end in a clinch entry rather than a retreat."],
  pacing: "Pankration has an aggressive, flowing pace with no clear separation between its phases. Striking flows into clinch, clinch flows into takedown, takedown flows into ground fighting without pause. The rhythm is the rhythm of one fighter imposing their will across all ranges without stopping.",
  writingNotes: "The historical Pankratiast was the most complete fighter in the ancient world. A character with this background carries the confidence of someone trained for all eventualities — there is no range of combat that surprises them.",
};
