import { pgTable, text, timestamp, integer, jsonb, varchar, uuid } from "drizzle-orm/pg-core";
import { relations } from "drizzle-orm";

export const users = pgTable("users", { id: uuid("id").defaultRandom().primaryKey(), name: text("name"), email: text("email").notNull().unique(), emailVerified: timestamp("email_verified",{mode:"date"}), image: text("image"), hashedPassword: text("hashed_password"), createdAt: timestamp("created_at").defaultNow().notNull(), updatedAt: timestamp("updated_at").defaultNow().notNull() });
export const accounts = pgTable("accounts", { id: uuid("id").defaultRandom().primaryKey(), userId: uuid("user_id").notNull().references(()=>users.id,{onDelete:"cascade"}), type: text("type").notNull(), provider: text("provider").notNull(), providerAccountId: text("provider_account_id").notNull(), refresh_token: text("refresh_token"), access_token: text("access_token"), expires_at: integer("expires_at"), token_type: text("token_type"), scope: text("scope"), id_token: text("id_token"), session_state: text("session_state") });
export const sessions = pgTable("sessions", { id: uuid("id").defaultRandom().primaryKey(), sessionToken: text("session_token").notNull().unique(), userId: uuid("user_id").notNull().references(()=>users.id,{onDelete:"cascade"}), expires: timestamp("expires",{mode:"date"}).notNull() });
export const projects = pgTable("projects", { id: uuid("id").defaultRandom().primaryKey(), userId: uuid("user_id").notNull().references(()=>users.id,{onDelete:"cascade"}), name: text("name").notNull().default("Untitled Project"), format: varchar("format",{length:50}).notNull().default("Novel"), genres: jsonb("genres").$type().default([]), notes: text("notes").default(""), createdAt: timestamp("created_at").defaultNow().notNull(), updatedAt: timestamp("updated_at").defaultNow().notNull() });
export const characters = pgTable("characters", { id: uuid("id").defaultRandom().primaryKey(), projectId: uuid("project_id").notNull().references(()=>projects.id,{onDelete:"cascade"}), name: text("name").notNull(), role: text("role").default(""), age: text("age").default(""), appearance: text("appearance").default(""), personality: text("personality").default(""), thinkingStyle: text("thinking_style").default(""), behavior: text("behavior").default(""), habits: text("habits").default(""), fears: text("fears").default(""), desires: text("desires").default(""), speechPattern: text("speech_pattern").default(""), backstory: text("backstory").default(""), arc: text("arc").default(""), sortOrder: integer("sort_order").default(0), createdAt: timestamp("created_at").defaultNow().notNull() });
export const locations = pgTable("locations", { id: uuid("id").defaultRandom().primaryKey(), projectId: uuid("project_id").notNull().references(()=>projects.id,{onDelete:"cascade"}), name: text("name").notNull(), description: text("description").default(""), atmosphere: text("atmosphere").default(""), history: text("history").default(""), sensoryDetails: text("sensory_details").default(""), sortOrder: integer("sort_order").default(0), createdAt: timestamp("created_at").defaultNow().notNull() });
export const plotThreads = pgTable("plot_threads", { id: uuid("id").defaultRandom().primaryKey(), projectId: uuid("project_id").notNull().references(()=>projects.id,{onDelete:"cascade"}), name: text("name").notNull(), description: text("description").default(""), status: varchar("status",{length:20}).default("Active"), stakes: text("stakes").default(""), connections: text("connections").default(""), sortOrder: integer("sort_order").default(0), createdAt: timestamp("created_at").defaultNow().notNull() });
export const chapters = pgTable("chapters", { id: uuid("id").defaultRandom().primaryKey(), projectId: uuid("project_id").notNull().references(()=>projects.id,{onDelete:"cascade"}), title: text("title").notNull().default("Chapter 1"), content: text("content").default(""), summary: text("summary").default(""), sortOrder: integer("sort_order").default(0), wordCount: integer("word_count").default(0), createdAt: timestamp("created_at").defaultNow().notNull(), updatedAt: timestamp("updated_at").defaultNow().notNull() });
export const referenceWorks = pgTable("reference_works", { id: uuid("id").defaultRandom().primaryKey(), projectId: uuid("project_id").notNull().references(()=>projects.id,{onDelete:"cascade"}), title: text("title").notNull(), attributes: jsonb("attributes").$type().default({}), createdAt: timestamp("created_at").defaultNow().notNull() });
export const generations = pgTable("generations", { id: uuid("id").defaultRandom().primaryKey(), projectId: uuid("project_id").notNull().references(()=>projects.id,{onDelete:"cascade"}), chapterId: uuid("chapter_id").references(()=>chapters.id,{onDelete:"set null"}), mode: varchar("mode",{length:20}).notNull(), prompt: text("prompt").notNull(), output: text("output").notNull(), model: varchar("model",{length:100}).default("claude-sonnet-4-20250514"), tokensUsed: integer("tokens_used"), createdAt: timestamp("created_at").defaultNow().notNull() });

export const usersRelations = relations(users, ({many})=>({projects:many(projects)}));
export const projectsRelations = relations(projects, ({one,many})=>({ user:one(users,{fields:[projects.userId],references:[users.id]}), characters:many(characters), locations:many(locations), plotThreads:many(plotThreads), chapters:many(chapters), referenceWorks:many(referenceWorks), generations:many(generations) }));
export const charactersRelations = relations(characters, ({one})=>({project:one(projects,{fields:[characters.projectId],references:[projects.id]})}));
export const locationsRelations = relations(locations, ({one})=>({project:one(projects,{fields:[locations.projectId],references:[projects.id]})}));
export const plotThreadsRelations = relations(plotThreads, ({one})=>({project:one(projects,{fields:[plotThreads.projectId],references:[projects.id]})}));
export const chaptersRelations = relations(chapters, ({one})=>({project:one(projects,{fields:[chapters.projectId],references:[projects.id]})}));
export const referenceWorksRelations = relations(referenceWorks, ({one})=>({project:one(projects,{fields:[referenceWorks.projectId],references:[projects.id]})}));
export const generationsRelations = relations(generations, ({one})=>({ project:one(projects,{fields:[generations.projectId],references:[projects.id]}), chapter:one(chapters,{fields:[generations.chapterId],references:[chapters.id]}) }));