import { NextResponse } from 'next/server';
import { getRequiredSession } from '@/lib/auth-helpers';
import { db } from '@/db';
import { projects } from '@/db/schema';
import { and, eq } from 'drizzle-orm';
import JSZip from 'jszip';
import { tiptapToPlainText, isValidTipTapJson } from '@/lib/editor/content-migration';

const PLATFORM_NOTES: Record<string, string> = {
  wattpad:   'Wattpad: Chapter titles show in the reading interface. First paragraph is critical for tap-through rate. No markdown formatting — Wattpad renders plain text with its own styling.',
  royalroad: 'Royal Road: Supports some HTML. Chapter descriptions appear in the table of contents. Tags affect discoverability heavily.',
  substack:  'Substack: Email delivery — keep chapters under 3000 words. Include a brief author note at the end for engagement.',
};

export async function POST(req: Request, { params }: { params: { projectId: string } }) {
  const session = await getRequiredSession();
  const { platform } = await req.json() as { platform: 'wattpad' | 'royalroad' | 'substack' | 'generic' };

  const project = await db.query.projects.findFirst({
    where: and(eq(projects.id, params.projectId), eq(projects.userId, session.user.id)),
    with: {
      chapters: { orderBy: (c, { asc }) => [asc(c.sortOrder)] },
      characters: { columns: { name: true, backstory: true, role: true } },
      locations: { columns: { name: true, description: true } },
    },
  });
  if (!project) return NextResponse.json({ error: 'Not found' }, { status: 404 });

  const getText = (content: string | null) => {
    if (!content?.trim()) return '';
    return isValidTipTapJson(content) ? tiptapToPlainText(JSON.parse(content)) : content;
  };

  const zip = new JSZip();
  const folder = zip.folder(project.name) ?? zip;

  (project as any).chapters.forEach((chapter: any, i: number) => {
    const epNum = String(i + 1).padStart(2, '0');
    folder.file(
      `episode-${epNum}-${chapter.title.replace(/[^a-z0-9]/gi, '_').toLowerCase()}.txt`,
      `${chapter.title}\n${'='.repeat(chapter.title.length)}\n\n${getText(chapter.content)}`
    );
  });

  const bibleLines = [
    `# ${project.name} — Series Bible\n`,
    `## Characters\n`,
    ...((project as any).characters ?? []).map((c: any) =>
      `### ${c.name}\n${c.role ? `Role: ${c.role}\n` : ''}${c.backstory ? c.backstory : ''}\n`
    ),
    `\n## Locations\n`,
    ...((project as any).locations ?? []).map((l: any) =>
      `### ${l.name}\n${l.description ?? ''}\n`
    ),
  ];
  folder.file('series-bible.md', bibleLines.join('\n'));

  const summaryLines = [
    `# ${project.name} — Episode Summaries\n`,
    ...(project as any).chapters.map((c: any, i: number) =>
      `**Ep ${i + 1}: ${c.title}**\n${c.summary || '_No summary yet_'}\n`
    ),
  ];
  folder.file('episode-summaries.md', summaryLines.join('\n'));

  folder.file('author-notes-template.md',
    `# Author Notes Template\n\nCopy and paste at the end of each episode:\n\n---\n*[Your author note here. Mention what's coming next, ask a question, thank readers.]*\n\n${platform !== 'generic' ? `Platform notes for ${platform}:\n${PLATFORM_NOTES[platform]}` : ''}`
  );

  folder.file('README.md',
    `# ${project.name} — Episode Pack\n\nGenerated by GhostWriter AI.\n\nContents:\n- episode-XX-title.txt — individual episode files\n- series-bible.md — characters and world reference\n- episode-summaries.md — one-paragraph summaries for each episode\n- author-notes-template.md — copy/paste template for author notes\n\n${platform !== 'generic' ? PLATFORM_NOTES[platform] : ''}`
  );

  const zipBuffer = await zip.generateAsync({ type: 'nodebuffer' });
  return new Response(zipBuffer as any, {
    headers: {
      'Content-Type': 'application/zip',
      'Content-Disposition': `attachment; filename="${project.name.replace(/[^a-z0-9]/gi, '_')}_episode_pack.zip"`,
    },
  });
}
