import type { CombatStyle } from "../../types";

export const GATKA: CombatStyle = {
  name: "Gatka",
  origin: "Punjab, India",
  era: "Sikh martial tradition rooted in the 15th–17th century; associated with the Nihang warriors; practiced today as both martial art and cultural performance.",
  corePhilosophy: "Gatka is a martial art of courage and commitment. The Sikh warrior tradition from which it comes teaches that the weapon is never drawn in anger but never sheathed in cowardice. The fighter moves with absolute commitment — there is no tentative action in Gatka. The sword and shield operate as a single system, not as separate tools: the shield controls the opponent's weapon while the sword finds the opening the shield created.",
  bodyMechanics: "The BNR dataset on sword-and-shield combat establishes the core mechanical principle: the shield is not passive armor but an active control tool. When the shield intercepts an incoming weapon, the practiced fighter rotates it to redirect the force sideways rather than absorbing it centrally. This redirection creates the opening the sword exploits — the opponent's weapon has been moved off their centerline, and the sword arrives before they can recover it. The pentra (footwork pattern) moves the body in a rotating pattern around the opponent — never retreating directly backward, always pivoting around the attack's line. The BNR data on circular footwork in weapon combat confirms that a lateral step of 45–60 degrees removes the body from the attack line while simultaneously creating a flanking angle that the sword can exploit.",
  distancePreference: "Mid-range — sword distance, with the shield controlling the entry.",
  footworkPrinciple: "The pentra pattern rotates around the opponent rather than moving away from them. The feet trace a circle whose center is the opponent — which means the Gatka fighter is always moving but never retreating.",
  stances: [
    { name: "Sword-Shield Guard", bodyPosition: "Shield forward and angled outward, sword behind the shield line ready to strike, feet in the pentra starting position.", weightDistribution: "55% front / 45% rear", strengths: "Shield controls the opponent's sight line and weapon access. Sword is hidden behind it.", weaknesses: "The shield commitment requires the front arm — if the shield is bypassed, the body is exposed." },
    { name: "Chakkar Ready", bodyPosition: "Chakkar (steel throwing disc) held at shoulder height, body angled for the throw, sword sheathed or in the off-hand.", weightDistribution: "50% front / 50% rear", strengths: "The chakkar threat changes the opponent's approach — they cannot simply advance.", weaknesses: "Once thrown, the chakkar is gone." },
  ],
  strikes: [
    { name: "Shield Redirect into Cut", mechanics: "The shield intercepts the incoming weapon at an angle — not perpendicular, which absorbs force, but at 45 degrees, which redirects it. The BNR impact interception data shows that a 45-degree interception dissipates approximately 70% of the impact force sideways rather than into the defender's arm. The opponent's weapon is moved off their centerline, and the sword arrives through the opened centerline simultaneously.", setup: "The opponent has committed to an attack.", execution: "The shield meets the weapon at 45 degrees, redirects it sideways, and the sword cuts through the opened centerline simultaneously.", recovery: "The shield returns to guard position immediately after the redirect.", counter: "Attack from two lines so the shield cannot cover both." },
    { name: "Chakkar Throw", mechanics: "The chakkar is a weighted steel throwing disc. The BNR data on thrown weapon mechanics shows that it achieves maximum rotational stability at a release angle of approximately 20 degrees above horizontal from a shoulder-height throw.", setup: "The opponent is at 6–15 metres and in the open.", execution: "Released at shoulder height with wrist rotation imparted for spin stability.", recovery: "After throwing, the fighter immediately closes to sword range.", counter: "Stay close to the Gatka fighter where the chakkar cannot be used safely." },
  ],
  defenses: [
    { name: "Pentra Pivot", mechanics: "Rather than blocking, the pentra moves the body around the attack line. The BNR footwork data confirms that a 45–60 degree lateral step removes the body from the attack line while positioning it to strike the attacker's exposed flank.", setup: "An attack is incoming.", execution: "The feet execute the pentra pivot — rotating the body around the attack rather than absorbing it.", recovery: "The pivot ends in a position to counterattack the attacker's now-exposed side.", counter: "Attack in combination — the pentra handles single attacks but has difficulty with simultaneous lines." },
  ],
  strengthAgainst: ["Single-weapon fighters who have no answer for the shield's active control.", "Aggressive forward movers whose commitment creates the opening.", "Opponents at throwing range who underestimate the chakkar."],
  weakAgainst: ["Multiple opponents who attack from different angles simultaneously.", "Grappling specialists who get inside the sword range.", "Ranged weapons at distances beyond chakkar effective range."],
  signatureTells: ["The shield is never flat — it is always slightly angled, ready to redirect rather than absorb.", "The feet never stop moving in the pentra pattern.", "The sword hand stays relaxed until the moment of the cut.", "The chakkar is checked with the thumb before any serious engagement begins."],
  pacing: "Gatka has a bold, rhythmic pacing. The pentra creates a constant rotation that gives it a ceremonial quality even in serious combat. When the shield and sword combination fires, the action is fast and decisive — then the pentra resumes.",
  writingNotes: "A Gatka practitioner carries themselves with the bearing of someone whose martial art is also a spiritual practice. They tend toward directness, moral clarity, and a certain ceremonial dignity even in casual situations.",
};

export const KUSHTI: CombatStyle = {
  name: "Kushti",
  origin: "India (Subcontinental wrestling tradition; major centers in Maharashtra, Punjab, Uttar Pradesh, and Bengal)",
  era: "Ancient Indian wrestling with roots in Vedic tradition; the akhara system has existed for over two millennia; still practiced today.",
  corePhilosophy: "Kushti is the art of the pehlwan — the earth wrestler. Training happens in the akhara on a pit of mixed earth, brick dust, oil, and cow dung. The ground itself becomes part of the fighter. Kushti teaches that strength means nothing without technique, and technique means nothing without the daily discipline of the body.",
  bodyMechanics: "The NTU RGB+D 120 dataset on wrestling techniques provides the most applicable data. For Kushti's core throws, the mechanical requirement is identical to what the dataset shows for all standing-to-ground grappling: the attacker must get their center of mass below the opponent's center of mass before the throw can complete mechanically. The dhobi pachad throw requires the thrower's hips to drop below the opponent's hip level during entry — approximately hip-to-mid-thigh height. From this position, the throw converts the height differential into rotational force. The dhobiyan follow-through — the practitioner staying connected through the throw and controlling the landing — reflects the Kushti philosophy of dominant top control.",
  distancePreference: "Close range — clinch and body contact. Kushti does not function at striking distance.",
  footworkPrinciple: "Heavy, grounded, and short. The pehlwan does not dance — they plant and apply pressure. Footwork is about positioning for the takedown entry.",
  stances: [
    { name: "Pehlwan Guard", bodyPosition: "Knees bent, hips low, torso slightly forward, arms wide and active, head up.", weightDistribution: "50% front / 50% rear", strengths: "Low center of mass resists takedowns. Wide arm position makes grip-fighting accessible.", weaknesses: "Committed to close range — cannot easily transition to striking distance." },
    { name: "Clinch Control", bodyPosition: "One arm over the opponent's shoulder (overhook), one arm under (underhook), head pressed against the opponent's shoulder or chest, hips driving forward.", weightDistribution: "55% front / 45% rear", strengths: "From here, all Kushti throws are available.", weaknesses: "If the underhook is lost, the position weakens significantly." },
  ],
  strikes: [
    { name: "Dhobi Pachad (Slam Throw)", mechanics: "The NTU throwing data establishes the requirement: the thrower's hips drop below the opponent's hips during entry. From the clinch, the pehlwan drops suddenly — a genuine hip-drop, not a lean — getting their center of mass below the opponent's. The throw converts the height differential into rotational force.", setup: "The clinch is established and both fighters are upright.", execution: "A sudden hip drop to below the opponent's hip level, then drive upward and rotate, carrying the opponent over the hip and driving them into the earth.", recovery: "The thrower follows the opponent to the ground and establishes top control immediately.", counter: "Widen the base and drop your own hips when the grip changes — denying the depth of the entry." },
    { name: "Dhobiyan (Ground Control)", mechanics: "Once the opponent is on the ground, the pehlwan establishes dominant top position. The NTU grappling data on ground control shows that head-and-hip alignment in top position prevents most escape attempts.", setup: "The opponent has been taken to the ground.", execution: "The pehlwan drops into top position with weight distributed through the chest and hips.", recovery: "If the opponent escapes to a half-guard position, the pehlwan uses weight and grip to return to dominant position.", counter: "Create frames before the top position is fully established — once the pehlwan's full weight is settled, escaping requires significantly more effort." },
  ],
  defenses: [
    { name: "Base and Sprawl", mechanics: "When a takedown is attempted, the pehlwan sprawls — driving the hips back and down, spreading the base wide, and dropping the weight onto the opponent's upper body to flatten the takedown attempt.", setup: "An opponent is attempting to lower their hips for a throw entry.", execution: "The hips drive backward and the body drops, putting weight on the opponent's back and flattening the entry.", recovery: "The pehlwan reestablishes an upright position with grips while the opponent recovers.", counter: "Change direction mid-entry — a sprawl commits the weight backward, and a sudden forward rush can off-balance the defender." },
  ],
  strengthAgainst: ["Opponents who stand upright and give clean grip access.", "Strikers who cannot maintain distance and allow clinch contact.", "Fighters who have no answer for being taken to the ground."],
  weakAgainst: ["Striking specialists who keep the fight at range and prevent the clinch.", "Opponents with superior grip-fighting who deny the entry.", "Multiple opponents in an environment where going to the ground is not safe."],
  signatureTells: ["The hips are always lower than the opponent's — the pehlwan is never standing fully upright.", "The hands are constantly probing for grip — not attacking, but testing.", "Weight shifts toward the front foot before a throw entry.", "The eyes watch the opponent's hips, not their hands."],
  pacing: "Kushti has a slow, grinding patience punctuated by sudden explosive throws. The grip-fighting phase can last a long time — both fighters testing and denying. When the entry comes, it is fast and definitive. The match should feel like a siege that ends with a collapse.",
  writingNotes: "A Kushti-trained character carries the physicality of the akhara in their body — not just muscle, but a specific quality of weight and groundedness. They tend toward patience, silence, and a directness that has no time for performance.",
};

export const MARDANI_KHEL: CombatStyle = {
  name: "Mardani Khel",
  origin: "Maharashtra, India",
  era: "Maratha martial tradition with roots in the 17th–18th century Maratha Empire; associated with the cavalry and infantry of the Maratha armies; practiced today in limited form.",
  corePhilosophy: "Mardani Khel is a martial art built for the battlefield, not the arena. The pata (gauntlet sword) and the vita (rope dart) are weapons that change the rules of engagement — the pata cannot be disarmed because it is attached to the forearm, and the vita can attack from distances that confound conventional sword range.",
  bodyMechanics: "The pata is mechanically unique because it attaches to the forearm via a gauntlet. Because the weapon cannot be dropped or disarmed, the forearm and sword become a single rigid unit. This changes the wrist's role — the wrist no longer steers the weapon as in a standard grip; instead, the entire forearm rotation steers the blade. Maximum forearm rotation is approximately 180 degrees, giving the pata a wider angular attack range than a handheld sword. The vita (rope dart) achieves peak velocity at approximately two-thirds of the rope's length into the cast — not at full extension as intuition suggests. Skilled vita users attack at the velocity peak, then recover the weapon for the next cast before the opponent has processed what happened.",
  distancePreference: "Variable — the pata operates at sword range, the vita operates at rope-length range (~3–4 metres).",
  footworkPrinciple: "The footwork adapts to which weapon is active. With the pata, footwork is forward-committed. With the vita, the practitioner stays at rope length and circles.",
  stances: [
    { name: "Pata Guard", bodyPosition: "The gauntlet arm forward and raised, the blade extending beyond the fist, body slightly angled.", weightDistribution: "55% front / 45% rear", strengths: "The gauntlet protects the forearm from counterstrikes. The blade is always positioned to attack.", weaknesses: "The gauntlet's weight fatigues the arm in extended exchanges." },
    { name: "Vita Ready", bodyPosition: "Rope coiled in the non-gauntlet hand, weighted tip hanging at waist height, body angled to allow a full cast rotation.", weightDistribution: "50% front / 50% rear", strengths: "The vita threat prevents opponent approach.", weaknesses: "The coiled rope requires space to deploy — useless in confined areas." },
  ],
  strikes: [
    { name: "Pata Forearm Cut", mechanics: "Because the blade is fixed to the forearm, the cut is driven by shoulder rotation and forearm supination/pronation rather than wrist steering. The effective arc is approximately 180 degrees from full pronation to full supination.", setup: "The opponent is at sword range and the pata arm is positioned.", execution: "The shoulder drives, the forearm rotates through supination to pronation, and the blade cuts through the arc.", recovery: "The forearm reverses rotation back to guard position.", counter: "Attack while the forearm is at the extremes of its rotation arc — supination and pronation are both momentarily slow to reverse." },
    { name: "Vita Cast", mechanics: "The vita achieves peak velocity at approximately two-thirds of the cast length. The practitioner casts the tip toward the target, attacks at the velocity peak, and recovers before the opponent can grab the rope or close distance.", setup: "The opponent is at rope length (3–4 metres) and in the open.", execution: "The rope casts from a coiled position, the tip accelerates through the arc, and the strike lands at peak velocity.", recovery: "The rope is recovered immediately by recoiling — the vita is never left fully extended.", counter: "Close inside rope length so the weapon cannot develop full velocity." },
  ],
  defenses: [
    { name: "Gauntlet Block", mechanics: "The gauntlet's thick metal forearm protection allows the pata fighter to block incoming sword strikes with the forearm rather than the blade — a unique defensive capacity. Blocking with the gauntlet preserves the blade's position for the immediate counter.", setup: "An incoming strike is aimed at the forearm or weapon hand.", execution: "The gauntlet arm raises to intercept the blow on the metal surface rather than the blade.", recovery: "The counter fires immediately from the block position.", counter: "Attack the unprotected arm or the body directly." },
  ],
  strengthAgainst: ["Fighters who target the weapon hand — the gauntlet protects it.", "Opponents at medium range who cannot deal with the vita's unpredictable cast angle.", "Disarming specialists — the pata literally cannot be disarmed from the hand."],
  weakAgainst: ["Close-range grapplers who can neutralize both weapons by controlling the body.", "Confined spaces where the vita cannot be deployed.", "Opponents who close inside vita range before it can be cast."],
  signatureTells: ["The gauntlet arm is never relaxed — the weight of the pata keeps it slightly raised even at rest.", "The vita-carrying hand keeps the rope coiled and slightly tensioned, ready to cast.", "The practitioner maintains a wider-than-normal distance from opponents.", "When the gauntlet arm moves, the blade moves with it."],
  pacing: "Mardani Khel has two distinct tempos that shift based on which weapon is active. The vita creates a controlled, circling distance game. When the pata becomes primary, the pace increases and the exchanges are committed and decisive.",
  writingNotes: "A Mardani Khel practitioner is at their most dangerous at the weapons' preferred ranges — a fact they are acutely aware of. They tend to manage distance deliberately in all contexts, positioning themselves where their options are best.",
};
