import type { CombatStyle } from "../../types";

export const HUYEN_LALLONG: CombatStyle = {
  name: "Huyen Lallong",
  origin: "Manipur, India",
  era: "Traditional martial art of Manipur; the unarmed component of the broader Manipuri martial tradition that includes Thang-Ta; still practiced today.",
  corePhilosophy: "Huyen Lallong is the empty-hand expression of the Manipuri warrior tradition. It teaches that the body itself is a complete weapons system — every part of it can strike, and every movement simultaneously creates offense and defense. The art is built on the principle of continuous motion: a fighter who is always moving is harder to hit and always generating the next attack.",
  bodyMechanics: "The continuous motion principle creates a distinctive mechanical profile. Rather than the stop-start mechanics of many striking arts (strike, recover, reset), Huyen Lallong strikes flow from one movement into the next without a discrete recovery phase. The KYO dataset's analysis of continuous-motion striking shows that the reduced peak force per strike is compensated by the increased frequency and the opponent's inability to predict the attack line. The art uses all limbs — fists, palm heels, elbows, knees, feet, and head — as interchangeable weapons depending on range.",
  distancePreference: "Variable — all ranges are used as the continuous motion transitions between them.",
  footworkPrinciple: "Fluid and circular. The feet never stop — they circle, slide, and pivot continuously, denying the opponent a stationary target while always positioning for the next attack.",
  stances: [
    { name: "Flow Guard", bodyPosition: "Hands moving in slow circular patterns, weight shifting continuously from foot to foot, body always slightly in motion.", weightDistribution: "Variable — constantly shifting", strengths: "No static target. The constant motion makes the timing of attacks unpredictable.", weaknesses: "Requires significant stamina to maintain. The continuous movement can be rhythmically timed by a patient opponent." },
  ],
  strikes: [
    { name: "Palm Heel Strike", mechanics: "A direct strike with the heel of the palm rather than the closed fist. The palm heel is more structurally stable than a bare-knuckle fist and can be used at closer range. The KYO data on palm-heel mechanics shows equivalent force to a closed fist punch with less risk of hand injury.", setup: "The practitioner is at punching range during a continuous flow exchange.", execution: "The arm extends from the flowing motion — there is no wind-up, the strike emerges from the existing movement.", recovery: "The arm continues its arc into the next movement rather than retracting.", counter: "Jam the shoulder before the arm extends — a jammed strike from a continuous-motion practitioner interrupts the entire flow." },
    { name: "Knee Strike", mechanics: "At close range, the knee drives upward into the opponent's midsection or downward onto a clinched opponent. The knee's mass and the hip drive behind it create significant force at close range.", setup: "The clinch range — the practitioner is inside punching distance.", execution: "The hip drives forward and upward, the knee rises sharply into the target.", recovery: "The knee drops back to the foot and the flow continues.", counter: "Sprawl backward to break the clinch range." },
  ],
  defenses: [
    { name: "Flowing Deflection", mechanics: "Rather than blocking, the practitioner uses a circular forearm movement to redirect incoming strikes. The deflection uses the opponent's force against them — the redirection adds their force to the practitioner's counter.", setup: "A strike is incoming.", execution: "The forearm sweeps in a circular arc to intercept and redirect the incoming strike, turning the deflection into the beginning of a counter.", recovery: "The deflecting arm continues its arc into the counter-strike without a separate recovery phase.", counter: "Attack after the deflection has committed — the practitioner's arm is extended in the arc." },
  ],
  strengthAgainst: ["Opponents who rely on timing discrete strikes — the continuous motion disrupts their timing patterns.", "Fighters who need recovery phases between attacks — Huyen Lallong gives no recovery windows.", "Opponents who telegraph with their shoulders or hips."],
  weakAgainst: ["Grapplers who close and hold — the continuous motion requires space to generate.", "Fighters with superior raw power who can stop the motion through impact.", "Any range beyond the art's striking envelope."],
  signatureTells: ["The hands are never completely still — even in a neutral position, they move slightly.", "The weight shifts before any strike — the continuous motion has its own rhythm that can be read.", "The eyes move as much as the body — tracking everything, committing to nothing."],
  pacing: "Huyen Lallong has a flowing, medium-paced rhythm punctuated by explosive moments. The continuous motion creates a hypnotic quality in observation — it can look like dance until the moment it isn't. The pacing should never fully stop.",
  writingNotes: "A Huyen Lallong practitioner is difficult to read in all contexts. They tend toward a relaxed, flowing quality in their movement and their thinking — they don't stop and they don't hurry. In fiction, they can feel almost meditative while being genuinely dangerous.",
};
