import type { CombatStyle } from "../../types";

export const INBUAN_WRESTLING: CombatStyle = {
  name: "Inbuan Wrestling",
  origin: "Mizoram, India (Mizo people)",
  era: "Traditional wrestling of the Mizo people; originated approximately 1750 CE in the village of Dungtlang; still practiced as a major sporting and cultural event.",
  corePhilosophy: "Inbuan wrestling has the most restrictive rules of any Indian grappling art — no leg holds, no stepping outside a small circle, no bending of the knees below a certain point. These constraints force practitioners into a mastery of upper-body control and balance disruption that is unlike any other wrestling tradition. Victory comes not through overpowering but through outbalancing.",
  bodyMechanics: "The constraint against knee-bending creates a mechanically unique upright grappling system. With the hips locked relatively high and knees near-straight, the primary leverage points shift entirely to the upper body — shoulders, arms, and torso rotation. The NTU RGB+D 120 dataset on upper-body grappling mechanics shows that in upright wrestling without leg attacks, the fighter who controls the opponent's centerline (the vertical axis through their hips and spine) controls the throw. Inbuan fighters grip the opponent's waist belt and use hip-to-hip contact as the primary leverage platform.",
  distancePreference: "Clinch range only — belt grips are established immediately.",
  footworkPrinciple: "Minimal and circular. The small circle boundary forces both fighters into constant micro-adjustments rather than large footwork movements. Victory requires staying inside the circle while putting the opponent outside it.",
  stances: [
    { name: "Belt Grip Guard", bodyPosition: "Both hands gripping the opponent's waist belt, bodies pressed hip-to-hip, head beside the opponent's head, knees only slightly bent.", weightDistribution: "50% front / 50% rear", strengths: "The belt grip gives immediate access to all hip-rotation throws. The upright posture makes the fighter hard to off-balance laterally.", weaknesses: "No leg attacks mean the throw options are limited to upper-body leverage. Fully committed to close contact." },
  ],
  strikes: [
    { name: "Hip Rotation Throw", mechanics: "With the belt grip established and hips in contact, the practitioner rotates their hips sharply while pulling the opponent's belt. The NTU data on upright throwing shows that hip rotation in an upright stance can generate enough force to throw without the depth entry required in lower-stance grappling, provided the opponent's feet are controlled or their balance is already compromised.", setup: "Both fighters are in belt grips, hip-to-hip contact established.", execution: "One foot steps to change the angle, the hips rotate sharply, the belt grip pulls the opponent in the direction of the rotation, and the opponent's balance breaks toward the circle boundary.", recovery: "Maintain the belt grip through the throw — releasing early reduces control of the landing.", counter: "Counter-rotate in the opposite direction to neutralize the throw's momentum." },
    { name: "Boundary Push", mechanics: "Rather than throwing, a boundary push uses sustained forward pressure to walk the opponent over the circle's edge. The mechanics favor the heavier fighter or the one with better foot placement — but leverage from the belt grip can overcome a weight disadvantage.", setup: "The practitioner has a directional advantage in the clinch.", execution: "Sustained hip drive forward and slightly sideways, pushing the opponent toward the boundary.", recovery: "After the opponent crosses the boundary, release the grip.", counter: "Redirect the push sideways by rotating the hips — change the direction of the force rather than opposing it." },
  ],
  defenses: [
    { name: "Circle Defense", mechanics: "The practitioner positions their feet so that any throw attempt would move them parallel to the circle boundary rather than toward it — always offering the thrower the longer path to the edge.", setup: "A throw attempt is incoming.", execution: "The feet reposition to make the circle boundary the throw's least efficient direction, forcing the opponent to work harder to reach the edge.", recovery: "Maintain the belt grip through the repositioning.", counter: "Change direction mid-attempt — a repositioning defender commits to a new foot placement that can be exploited by reversing." },
  ],
  strengthAgainst: ["Opponents with larger footwork who are disoriented by the small circle constraint.", "Fighters who rely on leg attacks — Inbuan rules remove the entire lower-body grappling game.", "Heavier opponents who depend on weight advantage rather than technique."],
  weakAgainst: ["Any system that uses leg attacks — the no-leg-attack rule is a sport constraint, not a capability gap for those rules don't apply.", "Fighters who are better at upper-body leverage within the belt-grip constraint."],
  signatureTells: ["The hands always seek the opponent's waist — the belt grip is the first priority, not the second.", "The hips stay high and close — there is no dropping for entries.", "The eyes watch the opponent's hips, not their hands."],
  pacing: "Inbuan wrestling has a tight, pressuring pace within the small circle boundary. The exchanges are continuous grip contests punctuated by explosive throw attempts. The art feels dense and close — both fighters pressed together with no retreating room.",
  writingNotes: "An Inbuan wrestler brings the constraint of the circle into all their fights — they think about boundaries, about where the edge is, about positioning relative to limits. In fiction, they tend to be strategically spatial thinkers.",
};
