import type { CombatStyle } from "../../types";

export const THANG_TA: CombatStyle = {
  name: "Thang-Ta",
  origin: "Manipur, India",
  era: "Ancient Meitei martial art of Manipur; associated with the Meitei royalty and warrior class; suppressed during the colonial period; revived in the 20th century.",
  corePhilosophy: "Thang-Ta — 'sword-spear' — is Manipur's primary weapons system. The art teaches that a weapon is not a tool held in the hand but an extension of the body's intention. The thang (sword) and ta (spear) each carry different philosophies: the sword teaches commitment and precision, the spear teaches reach and patience. A complete practitioner understands both weapons and can transition between them as distance changes.",
  bodyMechanics: "The BNR dataset on paired-weapon systems establishes the key mechanical distinction between the sword and spear in close combat. The thang (sword) generates maximum force through a cutting arc driven by hip rotation — the same kinetic chain as all power cutting weapons. The ta (spear) generates force through a thrust mechanics where the rear hand drives and the front hand guides angle — a linear force generation that reaches targets the sword cannot. When both weapons are used in combination, the art creates a threat envelope that covers all distances: the spear at long range, the sword at mid-range, and the empty hand as a final resort.",
  distancePreference: "Long range with the spear; mid-range with the sword. The practitioner manages distance to keep the opponent in the worst weapon's threat zone.",
  footworkPrinciple: "Forward-pressuring with the spear; circling with the sword. The practitioner uses the spear to control the opponent's approach and the sword to exploit any gap that opens.",
  stances: [
    { name: "Spear Guard (Ta)", bodyPosition: "Spear extended forward, rear hand at the butt, front hand at mid-shaft, body angled to present the smallest profile.", weightDistribution: "55% rear / 45% front", strengths: "Maximum reach. The opponent must pass through the spear's threat to reach the practitioner.", weaknesses: "A spear is slow to withdraw for a sword transition — the change of weapons is a vulnerable moment." },
    { name: "Sword Guard (Thang)", bodyPosition: "Sword raised and forward, body rotated to present the weapon-side, feet in a stable cutting stance.", weightDistribution: "55% front / 45% rear", strengths: "Full cutting arc available. Quick transitions to all directions.", weaknesses: "Shorter reach than the spear — the opponent can attack from outside the cutting range." },
  ],
  strikes: [
    { name: "Spear Thrust (Ta)", mechanics: "The rear hand drives forward, the front hand guides the angle, and the spear tip drives in a direct line toward the target. The BNR data on spear thrusting shows that the rear hand drive generates approximately 60% of the thrust's force — a weak rear hand produces a weak thrust regardless of front-hand placement.", setup: "The opponent is at spear range — beyond sword distance.", execution: "The rear foot steps forward slightly, the rear hand drives, the front hand adjusts angle, the tip arrives in a straight line.", recovery: "The spear withdraws along the same line immediately — an extended spear can be grabbed.", counter: "Deflect the tip sideways and close the distance — the spear is ineffective once inside its tip." },
    { name: "Sword Cut (Thang)", mechanics: "The hip rotation drives the sword in an arc — the same kinetic chain as all cutting weapon mechanics. The angle of the cut is determined by the stance at the moment of cutting.", setup: "The opponent is inside spear range but at sword distance.", execution: "The hip rotates, the shoulder follows, the arm drives the sword in a cutting arc through the target.", recovery: "The sword continues past the target and is repositioned for the next cut or the guard.", counter: "Jam the shoulder before the rotation completes." },
  ],
  defenses: [
    { name: "Weapon Cross-Block", mechanics: "The practitioner uses the sword to deflect the opponent's weapon sideways rather than blocking it perpendicular. The cross-block converts the incoming force into a sideways redirect, preserving the practitioner's own weapon position for the counter.", setup: "An attack is incoming.", execution: "The sword meets the incoming weapon at approximately 45 degrees, redirecting rather than absorbing.", recovery: "The redirect flows into the counter — the sword's position after the block is already positioned for the reply.", counter: "Attack from two simultaneous angles so one cannot be cross-blocked without exposing the other." },
  ],
  strengthAgainst: ["Opponents at a single range who cannot adapt when the weapons switch.", "Fighters with shorter weapons who must pass through the spear's threat to reach the practitioner.", "Opponents who commit to a direct line of attack — the spear threat dictates the approach path."],
  weakAgainst: ["Ranged weapons that outreach even the spear.", "Grapplers who close through the weapons at speed.", "Confined spaces where the spear cannot be maneuvered."],
  signatureTells: ["The spear hand checks the weapon's weight before any serious exchange — a habit from training.", "The eyes measure distance constantly — the practitioner is always calculating whether they are in sword or spear range.", "The weapon transitions (sword to spear, spear to sword) follow a specific grip pattern that can be recognized and timed."],
  pacing: "Thang-Ta has a deliberate, strategic pacing. The spear creates a long threat envelope that controls the approach. When the sword becomes primary, the pace increases. The art should feel like a chess game that suddenly becomes very fast.",
  writingNotes: "A Thang-Ta practitioner thinks in terms of range and weapon selection — every spatial position relative to an opponent is processed in terms of which weapon it favors. They tend toward strategic patience and decisive action once the right distance is achieved.",
};
