import type { DialogueArchetype } from "../types";

export const NEGOTIATION: DialogueArchetype = {
  name: "Negotiation",
  description: "Two parties who both want something the other has. Neither will show their real bottom line. The scene is a controlled exchange of partial truths in which both parties try to get more than they give while appearing to be reasonable.",
  underlyingConflict: "Both parties have a true minimum (what they will actually accept) and a stated position (what they open with). The gap between these is the negotiation's terrain. The winner is whoever forces the other to move toward their true minimum while revealing less of their own.",
  powerDynamic: "Power belongs to whoever needs the deal less — or can convincingly perform needing it less. The party who is more desperate loses. Information about desperation is therefore the scene's most dangerous commodity.",
  sceneStructure: "Opening positions (both parties state maximalist demands) — Probing (each party tests the other's real position — questions, reactions, silences) — First movement (someone concedes something — watch what they give to understand what they are protecting) — Escalation or breakdown (either the terms approach agreement or one party introduces a threat or walks) — Resolution (deal, breakdown, or standoff).",
  subtextRules: [
    "Neither party ever states their real bottom line — they work toward it from their maximum position.",
    "Every concession is a signal — what someone gives up tells you what they are protecting.",
    "Silence after an offer is power — the party who speaks first after an offer has been made concedes something.",
    "Appeals to fairness are tactical — 'that's not reasonable' means 'I can't accept that.'",
    "The party who introduced the meeting needed it more.",
  ],
  rhythmPattern: "Negotiation has a measured, deliberate rhythm — neither party should seem rushed. Long pauses are permitted and intentional. Exchanges can be short (offers and responses) or long (persuasion attempts). The rhythm speeds up when a deal is close and slows to near-stillness when a party is considering a major concession.",
  openingPrinciple: "Begin with both parties already in the room — the preamble is over. The opening line is an opening position, not a greeting. We are past social niceties. The first line should establish who came to ask and who came to be asked.",
  escalationMechanics: "Each round of exchange narrows the gap or introduces a new variable that changes the equation. Escalation is not conflict — it is increasing stakes. A party walking away is an escalation. Introducing a third party's interest is an escalation. Revealing a deadline is an escalation.",
  breakingPoint: "Either: the deal is made (both parties have moved to a position they can accept) or the negotiation breaks (one party walks, or introduces terms the other cannot meet). The breaking point in a successful negotiation is the moment of mutual recognition that the deal is the deal.",
  failureModes: [
    "Both parties are straightforwardly reasonable — one makes a fair offer, the other accepts it.",
    "Either party states their real bottom line early.",
    "The negotiation is about a single term — real negotiations have multiple variables that can be traded.",
    "Silence is not used — every pause is filled immediately.",
    "The outcome is determined by who is right, not by who is more skilled at the exchange.",
  ],
  systemDirectives: [
    "Neither character may state their real minimum — they work toward it from their opening position.",
    "Include at least one silence after an offer that lasts uncomfortably long.",
    "One character must concede something — and what they concede must reveal something about what they are protecting.",
    "The outcome must be determined by the exchange, not predetermined by either party's moral position.",
    "End with a deal, a breakdown, or a standoff — never with both parties still at their opening positions.",
  ],
  writingNotes: "The best negotiation scenes are uncomfortable because the reader can see both parties' real positions clearly even though neither party can. The tension comes from watching people perform confidence while uncertain, perform indifference while desperate.",
};

export const SEDUCTION: DialogueArchetype = {
  name: "Seduction",
  description: "A scene driven by desire that cannot be stated directly — at least not yet. The desire may be romantic, sexual, social, intellectual, or for power. What defines seduction is the indirection: both parties understand what is happening, and both maintain plausible deniability while the distance between them closes.",
  underlyingConflict: "One or both characters want something they cannot simply ask for. The asking must be disguised as something else — conversation, friendship, professional exchange. The conflict is between the desire for the thing and the risk of naming it directly.",
  powerDynamic: "The party who first names the desire explicitly loses power — they have made themselves vulnerable. The party who lets the other come to them maintains power. Seduction is often a performance of indifference by someone who is intensely interested.",
  sceneStructure: "Ordinary surface (a conversation about something neutral — neither party acknowledging the real subject) — First signal (an ambiguous line that could mean nothing or everything) — Response (the other party accepts or declines the ambiguity by matching it or deflecting) — Escalation of ambiguity (the signals get less deniable) — Threshold (the moment before either a declaration or a retreat) — Choice (someone either names it or they both step back).",
  subtextRules: [
    "Every compliment is a declaration. Every question is an invitation. Ordinary conversation becomes charged.",
    "Physical proximity and the awareness of it must be present — even in dialogue, the body is in the room.",
    "The line that means one thing on the surface and another thing underneath is the scene's basic unit.",
    "Deflection is not rejection — it is an invitation to come at it differently.",
    "The most powerful seduction lines create a situation where the other person must choose how to interpret them.",
  ],
  rhythmPattern: "Seduction has a slow, unhurried rhythm — both parties performing that they have nowhere to be, nothing to want. Lines are often longer than necessary, filled with details that serve to extend the time in each other's presence. Pauses are charged. The rhythm accelerates as the ambiguity becomes less deniable.",
  openingPrinciple: "Begin the scene before the seduction has started — in an ordinary exchange that the reader can see is already charged. The first line should be innocent of any obvious intent. The reader should notice the charge before the characters acknowledge it.",
  escalationMechanics: "Each exchange narrows the distance — physical or emotional. Escalation comes through: decreasing deniability of the signals, increasing physical proximity, disclosure of something personal (vulnerability is inviting), and the gradual removal of the subject that was serving as pretext.",
  breakingPoint: "The moment one party speaks without the protection of ambiguity — a direct declaration, an unambiguous touch, a confession of interest. Or the moment one party re-establishes deniability in a way that makes the subtext explicit by refusing it.",
  failureModes: [
    "Either party states their desire directly in the first half of the scene.",
    "The surface conversation is obviously pretextual — both characters are clearly there for the other thing.",
    "Physical awareness is absent — only words, no bodies in space.",
    "The seduction is one-sided — one character trying, the other clearly uninterested.",
    "The resolution is simple — either clearly yes or clearly no, without the ambiguity that defines the scene type.",
  ],
  systemDirectives: [
    "Maintain a surface conversation — something neutral that provides deniability for both parties.",
    "Every third or fourth line must carry double meaning — one innocent, one charged.",
    "Physical awareness must be present — distance, proximity, what each character notices about the other's body.",
    "Neither character may state desire directly until the scene's threshold moment.",
    "The ending must be ambiguous — even if something is decided, the decision should carry uncertainty.",
  ],
  writingNotes: "Seduction scenes fail when they become explicit too quickly or remain implicit for so long that the charge dissipates. The skill is in the calibration — keeping the charge high while maintaining the plausible deniability that gives the scene its tension.",
};

export const FAREWELL: DialogueArchetype = {
  name: "Farewell",
  description: "A parting that both characters know may be permanent, or one that carries the weight of a relationship changed beyond return. Not every goodbye — only the ones where something is ending. The scene is about what gets said in the last chance to say it, and what doesn't.",
  underlyingConflict: "One or both characters want the separation not to happen, or want to say something they have not said, or want to understand something they have not understood. Against this: the reality of the ending, which neither can stop.",
  powerDynamic: "The party who is leaving holds a kind of power — they have chosen their direction. The party who is staying is the one with less power over the outcome. But the staying party holds emotional power — they are the one being left with the last image.",
  sceneStructure: "The frame (both characters know this is a farewell) — Ordinary exchange (the last ordinary moments — practical details, surface talk) — The thing that needed saying (one character approaches what they have been holding) — The response (which may meet it, deflect it, or miss it entirely) — The actual leave-taking (the physical goodbye — how they part, what they do with their bodies) — The final moment (what one or both characters carry away).",
  subtextRules: [
    "The ordinary exchange is not ordinary — both characters are inhabiting it with unusual attention because it is the last time.",
    "What is not said is often what the scene is about — the declaration of love not made, the apology not given.",
    "Physical gestures at farewells carry enormous weight — a handshake when a hug was wanted.",
    "People at farewells often speak in shorthand — referencing shared history that the reader may not fully know, but should feel the weight of.",
    "False lightness — the person who is breaking apart performing ease — is one of the most powerful tools in this scene type.",
  ],
  rhythmPattern: "Farewell scenes have an uneven rhythm — some lines are quick (the practical details both are using to avoid the real thing) and some are very slow (the moments when the real thing is close). Time distorts in this scene type: the final minutes stretch.",
  openingPrinciple: "Begin in the last ordinary moment before the farewell becomes undeniable — before the bags are picked up, before the door is opened. The opening should feel like any other scene until the weight of what is coming lands.",
  escalationMechanics: "The scene escalates through the decreasing ability to avoid the real subject. The practical details run out. The time runs out. What has not been said becomes impossible to avoid — or becomes impossible to say, and the characters part without saying it.",
  breakingPoint: "Either: the thing that needed saying gets said — imperfectly, incompletely, but present. Or: the character who needed to say it does not say it, and the reader understands what is being lost in that silence.",
  failureModes: [
    "Characters say clean, complete goodbyes — every feeling articulated, every apology made, nothing left unresolved.",
    "The farewell is sentiment without specificity — generic expressions of feeling rather than particular, individual ones.",
    "The weight of the scene comes from the characters telling each other how they feel rather than from what they do and don't say.",
    "Physical leave-taking is skipped over — how people's bodies handle separation is as important as their words.",
  ],
  systemDirectives: [
    "Begin with practical, surface exchange — the real subject is approached, not opened with.",
    "Include at least one thing that is not said — the reader should feel its absence.",
    "Physical leave-taking must be written in detail — what each character does with their body at the moment of separation.",
    "At least one line must carry the full weight of the relationship history in a single ordinary-sounding sentence.",
    "The final image should be the one that lingers — the last thing one character sees of the other.",
  ],
  writingNotes: "The most memorable farewell scenes are specific. Not 'he said goodbye' but the exact inadequate words he found. Not 'she cried' but the particular way she held herself not to.",
};

export const GROUP_SCENE: DialogueArchetype = {
  name: "Group Scene",
  description: "Three or more characters in a scene where the dynamics between them are as important as what is said. Alliances form and shift. Someone gets silenced. Someone speaks through a third party. The group as a whole is a character with its own logic.",
  underlyingConflict: "In any group, there are multiple bilateral conflicts operating simultaneously — A vs B, B vs C, A vs C — and the group dynamic itself as a meta-conflict (the desire to maintain the group versus the individual desires that threaten it). Track all of them.",
  powerDynamic: "Group power is not held by one person — it circulates. The person with the most social power controls the subject. The person with the most information power controls the stakes. The person who is most willing to break the group's norms has a specific kind of power. Dynamics shift as these forms of power trade hands.",
  sceneStructure: "Establishment (the group and its current dynamic — who is with whom, who is in tension, who is performing for whom) — Disruption (an event, arrival, or disclosure that changes the balance) — Realignment (characters respond to the disruption, and the alliances shift) — Escalation (the new tensions come to the surface) — New state (the group has a different configuration than it started with).",
  subtextRules: [
    "Characters in groups often speak to one person while directing their real message at another.",
    "The group has a topic it is collectively avoiding — the scene's subtext.",
    "Silence in group scenes is socially charged — who does not speak, and when, reveals allegiance and fear.",
    "Laughter, particularly shared laughter at someone's expense, is a power tool.",
    "Two characters who were allied may drift apart mid-scene; two who were opposed may find common ground against a third.",
  ],
  rhythmPattern: "Group scenes have an irregular rhythm because multiple conversations are operating simultaneously. Some exchanges are between the full group; some are effectively bilateral. The rhythm should reflect this — not orderly round-robin but the natural chaos of multiple people in a room.",
  openingPrinciple: "Begin with the group already assembled, but not yet in the scene's real business. Let the reader map the relationships from the opening exchanges — who sits near whom, who addresses whom, who watches whom — before the disruption that drives the scene arrives.",
  escalationMechanics: "Group scenes escalate through accumulation — small realignments adding up. A joke lands that shouldn't. An alliance forms in front of someone who is excluded. A secret is glanced at but not spoken. By the time the real confrontation arrives, the ground has already shifted under everyone.",
  breakingPoint: "The moment when the subtext — the thing the group has collectively been avoiding — enters the room explicitly. It may be named, or it may be acted out. After the breaking point, the group's configuration is permanently altered.",
  failureModes: [
    "Characters take polite turns speaking — no cross-talk, no interruptions, no silencing.",
    "Every character has the same relationship to the scene's central conflict — no individual stakes.",
    "The group dynamic does not change — the scene ends with the same alliances it began with.",
    "One character dominates the scene completely — no challenge to their position.",
    "The scene's subject is addressed directly from the opening — no collective avoidance to be disrupted.",
  ],
  systemDirectives: [
    "At least one character must be silenced or interrupted during the scene.",
    "At least one exchange must be between two characters but directed at a third.",
    "The alliances at the scene's end must be different from its beginning.",
    "Include at least one moment of collective behavior — shared laughter, shared silence, shared discomfort.",
    "Not every character needs equal time — the distribution of speech is itself a power map.",
  ],
  writingNotes: "Group scenes are the hardest to write and the most rewarding to read when done well. The solution is to know, before writing, what the group is collectively avoiding — and let every character's behavior be shaped by their relationship to that avoidance.",
};
