// src/lib/tension/types/all-tension.ts
import type { TensionArchetype } from "../types";

export const SUSPENSE: TensionArchetype = {
  name: "Suspense",
  theoreticalBasis: "Brewer & Lichtenstein (1982) Structural Affect Theory: suspense is generated by postponing the story's outcome. The reader knows an event is coming and waits for it. Key finding: suspense can be evoked even when readers know how the story will end — the emotion is about the waiting, not the surprise. The reader doesn't need to not know the outcome; they need to not have it yet.",
  coreDescription: "Suspense is the reader ahead of the character. The reader has information that lets them predict the threat; the character does not see it coming. The tension is the distance between what the reader knows and what the character is doing about it. Closing that distance is the suspense.",

  discourseStructure: "Present the threat or outcome condition early, then delay its arrival. The reader is told or shown that something dangerous will happen, then the narrative moves toward that moment while the character moves through ordinary business. Hitchcock's bomb under the table: tell the audience the bomb is there, then show them a conversation about nothing. Two minutes of suspense instead of two seconds of surprise.",

  informationState: {
    readerKnows: "The threat exists. Its nature. Possibly its timing.",
    characterKnows: "Less than the reader. The character is unaware, or not fully aware, of the approaching threat.",
    gap: "The gap is the scene's engine. The reader is trying to close it by reading faster; the narrative widens it by proceeding deliberately. Every sentence that does not address the threat is a widening. Every moment that brings the threat closer is both a narrowing and an escalation.",
  },

  buildMechanics: "Introduce the threat early and concretely. Then proceed with other business. The threat's presence is felt in everything that happens after its introduction — the ordinary conversation, the task, the journey — because the reader knows what is behind it. Build suspense by increasing the apparent gap between the character's attention and the threat's approach.",

  sustainMechanics: "The threat must be credible and significant. Lazarus appraisal theory (1991): tension requires perceived significance plus outcome uncertainty. Remove either — make the threat seem minor or make the outcome seem certain — and the tension collapses. Sustain by: adding evidence that the threat is real, giving the character one or two near-misses, and delaying resolution without resolving it.",

  releaseOrWithhold: "Suspense ends in one of three ways: the threat arrives (resolution through event), the threat is narrowly avoided (resolution through near-miss), or the threat remains permanently suspended (the threat never resolves, which produces a different quality of dread). False resolution — appearing to resolve then reactivating — is the most powerful tool.",

  pacingRules: "The sentence level serves the suspense. Short sentences accelerate; long sentences delay. A long sentence in a suspenseful scene is a widening of the gap — the reader must go through it before the next step. Withhold clause resolution: 'She reached for the door, which was — she stopped.' The technique of grammatical suspension mirrors the emotional one.",

  tensionKillers: [
    "Explaining the threat fully and immediately — the reader stops worrying once they understand it completely",
    "The character behaves as though the threat exists — they should not; the gap requires their unawareness",
    "Too many qualifications — 'perhaps', 'maybe', 'seemed' reduce threat credibility",
    "Resolution that arrives exactly when expected — the tension of suspense requires that arrival be slightly wrong",
    "The threat being described rather than felt — a bomb is not frightening as information; it is frightening as the reason a conversation about nothing has unbearable weight",
  ],

  systemDirectives: [
    "Establish the threat before the scene's ordinary business. Then proceed with the ordinary business.",
    "The character must not know what the reader knows — maintain the information gap actively.",
    "Short sentences as threat approaches. Long sentences in ordinary business. Sentence rhythm is pacing.",
    "Include at least one grammatical suspension that mirrors the emotional suspension.",
    "False resolution: appear to resolve the threat, then reactivate it.",
  ],

  failureModes: [
    "The character behaves with appropriate fear throughout — suspense requires the character to NOT feel what the reader feels.",
    "The threat is resolved at first appearance — suspense is the delay, not the event.",
    "The outcome is stated rather than felt — 'she didn't know she was in danger' is a statement about the information gap, not an experience of it.",
    "The pacing is uniform — sentence length should vary with threat proximity.",
  ],

  writingNotes: "The most important Brewer & Lichtenstein finding for writers: you cannot use surprise and suspense simultaneously. If you show the bomb, you build suspense. If you hide it, you get two seconds of surprise. Suspense is always the better choice for sustained tension. Tell the reader what is coming. Then make them wait.",
};

export const CURIOSITY: TensionArchetype = {
  name: "Curiosity",
  theoreticalBasis: "Brewer & Lichtenstein (1982): curiosity is evoked by presenting the outcome before the preceding events. The reader sees the end-state and works backward to understand how it came to be. Unlike suspense (forward-looking), curiosity is retrospective: what happened?",
  coreDescription: "Curiosity is the reader behind the story. The narrative shows the consequence before the cause. The reader is in possession of the outcome and trying to understand how it arrived. This structure produces a different tension from suspense: not 'what will happen?' but 'how did we get here?'",

  discourseStructure: "Begin with the outcome: the body, the ruin, the character in the state they arrived at. Then move backward through the events that produced it. The Brewer & Lichtenstein discovery: presenting the outcome first makes readers more cognitively engaged in story processing — they are actively working to construct the causal chain, not passively receiving it.",

  informationState: {
    readerKnows: "The outcome — the end-state, the consequence, the result. But not the cause.",
    characterKnows: "The reader does not have access to the character's full knowledge of events; the narrative is structured to withhold the causal sequence.",
    gap: "The gap is the cause — the events, decisions, and circumstances that produced the known outcome. Closing this gap is the reader's work and pleasure.",
  },

  buildMechanics: "The outcome must be presented with enough specificity and weight that the reader genuinely wants to understand it. A generic bad outcome produces mild curiosity; a highly specific, unusual, or evocative outcome produces strong curiosity. The more exactly wrong or strange the outcome, the stronger the need to understand it.",

  sustainMechanics: "Reveal the cause incrementally, never completely. Each revelation changes the question: not 'how did she end up in that room?' but 'why did she go back?' Each answer produces a new question of greater specificity. The information is released in parcels that each generate the next question.",

  releaseOrWithhold: "Curiosity requires eventual resolution — the reader needs the cause. But the path to the cause can be extended indefinitely by each answer generating a new more specific question. The risk of over-withholding: the reader's frustration tips from pleasurable to aversive. Resolution that arrives slightly before the reader expects it is the optimal timing.",

  pacingRules: "Curiosity allows longer sentences than suspense — the reader is actively processing rather than anxiously waiting. But revelation sentences should be short and declarative: the answer, when it comes, should be delivered plainly. The contrast between the long path to the answer and the short delivery of the answer itself is the satisfaction.",

  tensionKillers: [
    "An outcome that is not specific enough to generate genuine need-to-know",
    "Revealing the cause too quickly — curiosity requires the reader to actively wonder",
    "Revealing the full cause in one exposure — incremental revelation sustains longer than single revelation",
    "An outcome that is too confusing — the reader must be able to imagine enough plausible causes to want the real one",
  ],

  systemDirectives: [
    "Open with the outcome — specific, unusual, or evocative enough to generate genuine curiosity.",
    "Reveal cause incrementally: each answer generates the next question.",
    "Short, declarative delivery of revelations: the contrast with the long path is the satisfaction.",
    "Each revelation should slightly change the frame — not just 'and then' but 'which means that'.",
  ],

  failureModes: [
    "The outcome is revealed so gradually that the reader never has a clear sense of what they are trying to understand.",
    "The cause is revealed in a single explanation scene — the information should arrive in pieces.",
    "The outcome is generic rather than specific — specificity is what makes it interesting.",
    "The causal chain, once revealed, doesn't feel earned by the outcome's weight.",
  ],

  writingNotes: "Curiosity-structure is the detective story, the cold-open mystery, the scene that begins at the wrong end. Its pleasure is retrospective understanding — the satisfaction of the puzzle assembling. Brewer and Lichtenstein found this structure produced better cognitive processing and better memory of story events than chronological structure. The reader works harder and remembers more.",
};

export const DREAD: TensionArchetype = {
  name: "Dread",
  theoreticalBasis: "Lazarus appraisal theory (1991): threat requires perceived significance + uncertainty about outcome. Dread is sustained threat without resolution — the sustained activation of the threat-appraisal system without the discharge event. Unlike suspense (which has a specific approaching event), dread is atmospheric: the threat is real but its form and timing are unknown.",
  coreDescription: "Dread is suspense without a specific bomb. The reader and character both feel that something is wrong, that something will happen, but neither can specify what or when. Dread is produced by environmental and behavioral signals that accumulate without resolving into a specific threat. It is more exhausting than suspense and more pervasive.",

  discourseStructure: "Accumulate threat signals without identifying a specific threat. The phone call that doesn't come. The door that wasn't there yesterday. The person who has changed in a way that cannot be named. Each signal is ambiguous; each could be nothing; together they form a pattern the reader's threat-detection system recognizes before the character can articulate it.",

  informationState: {
    readerKnows: "Something is wrong. The signals are present. But the threat is not specified.",
    characterKnows: "Something is wrong, but the character either cannot identify it or is actively refusing to identify it. The refusal to name the threat is as important as the threat.",
    gap: "The gap is between sensory reality (something is wrong) and cognitive resolution (what is wrong). This gap cannot be closed by information — it can only be closed by the threat manifesting or the character naming it. Keeping the gap open is the work of dread.",
  },

  buildMechanics: "Small, specific sensory anomalies that do not individually justify concern. The smell that should not be there. The timing that is wrong. The behavioral pattern that has shifted by one degree. Each anomaly, explained individually, has an innocent reading. Together they accumulate toward a pattern that the reader's limbic system recognizes as threat before the narrative names it.",

  sustainMechanics: "Dread sustains through refusal to resolve. Do not name the threat. Do not have the character realize what the reader has realized. Continue to add anomalies that fit the pattern. The character continuing to not-know, in the face of accumulating signals, is itself a source of dread: why won't they see what we see?",

  releaseOrWithhold: "Dread can resolve in two ways: the threat manifests (and becomes a different tension type) or the threat never manifests (and the story ends in a state of permanent unresolved wrongness). The second is the more disturbing, because the reader's threat-appraisal system has no discharge event.",

  pacingRules: "Dread operates at slow pace. The anomalies are delivered in ordinary prose, not in heightened language. The horror of dread is that it is indistinguishable from normalcy — the same sentence rhythm that describes breakfast describes the wrongness. The reader becomes unsure which sentences are normal and which are signals.",

  tensionKillers: [
    "Naming the threat — dread requires ambiguity; a named threat becomes suspense or horror",
    "Anomalies that are too obviously sinister — dread requires that each anomaly have a plausible innocent explanation",
    "The character reacting proportionally to the signals — a character who is also frightened converts dread to fear",
    "Resolution — dread accumulates; any satisfying resolution dissipates it",
    "Elevated prose that announces 'this is the frightening part' — dread is indistinguishable from normalcy",
  ],

  systemDirectives: [
    "Every anomaly must have a plausible innocent explanation — ambiguity is non-negotiable.",
    "The character must not fully see what the reader sees — maintain the refusal-to-see.",
    "Ordinary prose throughout — the frightening sentences must not sound frightening.",
    "Accumulate five to seven anomalies before any resolution — pattern recognition requires multiple data points.",
    "Do not name the threat. Do not allow it to be named.",
  ],

  failureModes: [
    "The dread is announced: 'something was wrong' — dread must be felt, not stated.",
    "The anomalies are obviously sinister rather than plausibly innocent.",
    "The character behaves as though they understand the threat.",
    "The resolution relieves all accumulated tension — dread's ending should leave some of the dread intact.",
  ],

  writingNotes: "Dread is the hardest tension type to write because it requires the writer to trust ambiguity completely. The moment you explain the wrongness, you destroy the dread. The wrongness must remain nameless. The reader's threat-appraisal system will do the work — it is older and faster than the conscious mind and will register the pattern before the reader can articulate why they feel uneasy. Trust it.",
};

export const PARANOIA: TensionArchetype = {
  name: "Paranoia",
  theoreticalBasis: "The unreliable perception model: the character's threat-detection system may be miscalibrated. The reader cannot determine whether the threat is real or constructed. This produces a specific anxiety that differs from dread (objective signals) — paranoia inverts the information asymmetry: the character perceives more threat than the reader can confirm.",
  coreDescription: "Paranoia is the character ahead of the reader. The character has concluded that the threat is real; the reader cannot confirm or deny it. The tension comes from the reader's uncertainty about whether the character's perception is accurate. Everything the character cites as evidence is ambiguous — it could confirm the threat or reveal a mind that has miscalibrated.",

  discourseStructure: "Present the character's threat perception first-person or close-third. Then present the evidence they are using. Then allow the reader to see an alternative explanation for that evidence. Maintain both interpretations simultaneously throughout the narrative. Never resolve in favor of either reading until the scene demands it — and even then, do it incompletely.",

  informationState: {
    readerKnows: "The character believes the threat is real. The evidence the character cites.",
    characterKnows: "More than the reader — the character is the source of threat-detection. But the reader cannot verify the character's perception.",
    gap: "The gap is epistemological: is the character's threat-detection accurate? This gap can only be resolved by events — and good paranoia narrative keeps events ambiguous too.",
  },

  buildMechanics: "Each piece of evidence the character cites must have two possible readings: threat-confirmation and innocent explanation. The balance between these readings shifts slightly over the scene — at first, the innocent explanation is dominant; by mid-scene, both are equally plausible; by the end, neither is clearly dominant.",

  sustainMechanics: "The character's behavior must be consistent with their threat perception — they would not act otherwise. But their behavior must also be consistent with a miscalibrated threat response. A character who locks all the doors could be right or could be experiencing persecutory ideation. Both must remain true.",

  releaseOrWithhold: "Paranoia can resolve three ways: the threat was real (character vindicated), the threat was not real (character's perception was miscalibrated), or the threat's reality is never resolved. The third is the most interesting for literary purposes and the most honest about how paranoia actually feels.",

  pacingRules: "Paranoia pacing mirrors the character's mental state: rapid-fire cataloguing of evidence, then sudden slow elaboration on a single detail, then rapid again. The rhythm itself signals the quality of the character's attention.",

  tensionKillers: [
    "Resolving the ambiguity early in favor of either reading",
    "Evidence that can only be explained by the threat — the innocent explanation must always be available",
    "A character whose threat-detection history is unambiguously reliable",
    "Other characters validating the paranoid character's perception — external validation collapses the ambiguity",
  ],

  systemDirectives: [
    "Every piece of evidence cited by the character must have an innocent reading.",
    "Do not validate the character's perception through another character's agreement.",
    "The character's behavior must be explicable by both accurate and inaccurate threat detection.",
    "Maintain both interpretations until the last possible moment.",
  ],

  failureModes: [
    "The character is clearly right or clearly wrong — paranoia requires genuine ambiguity.",
    "The evidence is only explicable through the threat.",
    "Another character confirms the threat — external validation resolves the tension.",
    "The character articulates their paranoia as if aware it might be paranoia — actual paranoia does not feel like paranoia from the inside.",
  ],

  writingNotes: "Paranoia is uniquely powerful because it turns the reader against themselves — they want to believe the character, but the evidence allows doubt, and the doubt makes them feel unkind, and the unkindness makes them more invested. The reader is doing the same work as the character: trying to determine what is real. That shared epistemological uncertainty is the specific pleasure of paranoia narrative.",
};

export const COUNTDOWN: TensionArchetype = {
  name: "Countdown / Ticking Clock",
  theoreticalBasis: "Brewer & Lichtenstein suspense-structure applied to explicit temporal constraint: the outcome is known, the timing is known, the distance to the outcome is measurable and decreasing. This is the most mechanical tension type and the most reliable — the reader cannot deny that the clock is running.",
  coreDescription: "Countdown is suspense made explicit. The deadline is stated. The reader and character both know what will happen and when. The tension is in the gap between available time and required action — and the obstacles that consume the time.",

  discourseStructure: "Establish the deadline and its consequence early and concretely. Then introduce the actions required to prevent the consequence. Then introduce obstacles that consume the time available for those actions. The narrative proceeds as a series of time-consuming obstacles against a stated deadline.",

  informationState: {
    readerKnows: "The deadline. Its consequence. The actions required. The time remaining.",
    characterKnows: "The same as the reader, or slightly less — the character may not know how much time an obstacle will consume.",
    gap: "The gap is between available time and required action. Every scene and every obstacle exists to change this gap.",
  },

  buildMechanics: "The deadline must be concrete and its consequence must be genuine — a deadline without a real consequence is not a countdown. Then each obstacle must consume a measurable and believable amount of time. The tension builds as the ratio between remaining time and remaining tasks deteriorates.",

  sustainMechanics: "Obstacle variety: not just new obstacles but obstacles that require different kinds of problem-solving. The setback that adds time (a complication that must be solved before proceeding). The partial success that consumes time without fully advancing the task. The unexpected resource that saves time (use sparingly — it deflates tension).",

  releaseOrWithhold: "Countdown resolves when either the deadline is met (success under wire), the deadline is missed (consequence arrives), or the deadline is extended (use very carefully — it resets the tension architecture and can feel like cheating). The closest success — the last possible moment — is the most satisfying resolution.",

  pacingRules: "Countdown pacing is controlled by time markers. The reader must always know approximately how much time remains. These markers can be explicit ('twelve minutes') or felt ('she hadn't heard the church bell again yet'). As the deadline approaches, the markers should become more frequent. Sentence length shortens as the clock runs down.",

  tensionKillers: [
    "Unclear stakes — if the consequence of missing the deadline is not concrete and significant, the countdown is meaningless",
    "Obstacles that feel manufactured rather than necessary — each obstacle must be believable as arising from the situation",
    "Time markers that are inconsistent or absent",
    "The unexpected resource that saves too much time too easily",
    "Resolution that arrives comfortably before the deadline — the wire must be felt",
  ],

  systemDirectives: [
    "The deadline and its consequence must be stated concretely early.",
    "Time markers must appear at regular intervals — the reader must always know where they are.",
    "Each obstacle must consume a believable amount of time.",
    "Shorten sentences as the clock runs down.",
    "The resolution must arrive within the last margin — let the wire be felt.",
  ],

  failureModes: [
    "The countdown is introduced but the time markers are absent — the reader loses track of the clock.",
    "The consequence of missing the deadline is soft or ambiguous.",
    "Obstacles are resolved too quickly — the time cost must be felt.",
    "The resolution arrives too comfortably before the deadline.",
  ],

  writingNotes: "Countdown is the tension type that requires the least craft and the most reliability. The mathematics of time against task is universally understood and universally felt. The risk is that it becomes mechanical — a series of obstacles without emotional texture. The best countdown narratives layer emotional content inside the mechanical structure: the obstacle is not just a problem to solve but a relationship that complicates, a memory that intrudes, a truth that makes the action harder. The clock gives you the structure; the emotion gives you the reason to care.",
};
