import { spawn } from "node:child_process";
import { writeFile, unlink, readFile, mkdtemp } from "node:fs/promises";
import { tmpdir } from "node:os";
import path from "node:path";
import ffmpegPath from "ffmpeg-static";

async function runFfmpeg(args: string[]): Promise<void> {
  await new Promise<void>((resolve, reject) => {
    const proc = spawn(ffmpegPath as unknown as string, args);
    let stderr = "";
    proc.stderr.on("data", (chunk: Buffer) => { stderr += chunk.toString(); });
    proc.on("error", reject);
    proc.on("close", (code: number) => {
      if (code === 0) resolve();
      else reject(new Error(`ffmpeg failed (exit ${code}): ${stderr}`));
    });
  });
}

/**
 * Properly concatenates independently-generated TTS audio buffers into one
 * valid, seamless file. Real bug this replaces: audio/generate/route.ts used
 * to do `Buffer.concat(audioBuffers)` — raw byte concatenation of separate
 * MP3 encodes. That's fragile: frame boundaries, headers, and bitrate
 * metadata from each independent TTS call don't reliably form one continuous
 * playable stream, unlike properly decoding and re-muxing through ffmpeg's
 * concat demuxer (confirmed against how the open-source podcastfy project
 * does this same job with pydub's AudioSegment — same underlying idea, ffmpeg
 * instead since that's already this codebase's own audio/video tool).
 *
 * Optionally inserts a short silence between segments (natural pacing for
 * multi-turn narration/dialogue — a single Buffer.concat has no room for
 * this at all) and loudness-normalizes the whole result to a fixed target
 * (EBU R128 single-pass loudnorm, -16 LUFS / -1.5 dBTP / LRA 11 — standard
 * podcast-loudness defaults) so segments generated by different calls (or
 * different voices) don't jump in perceived volume.
 */
export async function concatAudioBuffers(
  buffers: Buffer[],
  opts: { pauseMs?: number; normalize?: boolean } = {}
): Promise<Buffer> {
  if (buffers.length === 0) throw new Error("concatAudioBuffers requires at least one buffer");
  const { pauseMs = 0, normalize = true } = opts;

  const dir = await mkdtemp(path.join(tmpdir(), "gw-audio-concat-"));
  const cleanup: string[] = [];

  try {
    const segmentPaths: string[] = [];
    for (let i = 0; i < buffers.length; i++) {
      const p = path.join(dir, `segment-${i}.mp3`);
      await writeFile(p, buffers[i]);
      segmentPaths.push(p);
      cleanup.push(p);
    }

    let silencePath: string | null = null;
    if (pauseMs > 0 && buffers.length > 1) {
      silencePath = path.join(dir, "silence.mp3");
      await runFfmpeg([
        "-y",
        "-f", "lavfi",
        "-i", "anullsrc=r=24000:cl=mono",
        "-t", String(pauseMs / 1000),
        "-q:a", "9",
        silencePath,
      ]);
      cleanup.push(silencePath);
    }

    const listLines: string[] = [];
    segmentPaths.forEach((p, i) => {
      listLines.push(`file '${p}'`);
      if (silencePath && i < segmentPaths.length - 1) listLines.push(`file '${silencePath}'`);
    });
    const listPath = path.join(dir, "list.txt");
    await writeFile(listPath, listLines.join("\n"));
    cleanup.push(listPath);

    const outputPath = path.join(dir, "output.mp3");
    cleanup.push(outputPath);

    // Re-encoding (not -c copy) is deliberate: this is what actually fixes the
    // seam/header problem, and it's what lets loudnorm run at all.
    const args = ["-y", "-f", "concat", "-safe", "0", "-i", listPath, "-c:a", "libmp3lame"];
    if (normalize) args.push("-af", "loudnorm=I=-16:TP=-1.5:LRA=11");
    args.push(outputPath);

    await runFfmpeg(args);

    return await readFile(outputPath);
  } finally {
    await Promise.all(cleanup.map(p => unlink(p).catch(() => {})));
  }
}
