// src/lib/horror/archetypes/all-horror.ts
import type { HorrorArchetype } from "../types";

export const UNCANNY: HorrorArchetype = {
  name: "Uncanny",
  theoreticalBasis: "Freud's Das Unheimliche (1919): the uncanny arises when the familiar becomes strange. The German heimlich means homely and safe; unheimlich is its opposite. The horror is not produced by the alien or the obviously monstrous — it is produced by the ordinary thing that has become subtly wrong. The childhood home you return to find rearranged by a centimetre. The person who moves almost correctly. The machine that almost breathes. Freud traced this to the return of repressed animistic beliefs — the adult mind has suppressed the childhood sense that objects are alive, and when something makes that belief feel suddenly possible again, the result is the uncanny.",
  coreDescription: "Uncanny horror is produced by the violation of the expected rather than the introduction of the new. Something that should mean safety now means threat. Something that should be still is almost moving. Something that should be dead is almost alive. The reader recognizes the thing — and that recognition is the horror.",
  baselineRequirement: "The safe version must be established before the uncanny version can register. If the reader never believed the house was home, the wrongness has nothing to violate. Spend real time on the normal. Make the reader comfortable. Then introduce the deviation so small they almost dismiss it.",
  onsetMechanics: "The uncanny arrives in the gap between what is registered and what is acknowledged. The character notices something but does not quite name it. The body knows before the mind: a reluctance to enter a room, a hand that pauses on a doorknob without reason. The first uncanny signal must be ambiguous — it could be nothing. The second one confirms it. The third one makes the first two retroactively terrifying.",
  escalationPattern: "Accumulation without resolution. Each uncanny signal adds to the previous ones without explaining them. The explanation, when it arrives, must be worse than the ambiguity. Never explain the uncanny before the reader is fully in it — premature explanation converts dread to puzzle.",
  psychologicalMechanisms: [
    "Freud's return of the repressed: the animistic belief the adult mind has suppressed returns as dread",
    "The animate/inanimate boundary violation: the thing that is still when watched and moves when not",
    "The double (Doppelgänger): a copy of the self that exists outside the self's control",
    "The familiar made strange: the childhood home, the family member, the trusted object — now wrong",
    "Haidt's disgust: category violation (alive+dead, familiar+threatening) triggers the involuntary disgust response",
  ],
  readerSomaticTarget: "Skin prickling at the back of the neck. The reluctance to look at the corner of the room. The sense that the familiar object is being watched rather than watching. Not acute fear — sustained wrongness that the reader cannot pin down.",
  sacredRules: [
    "Never name the wrongness directly — 'it was uncanny' destroys the effect",
    "Establish the safe baseline before introducing any deviation",
    "The first signal must be dismissable — let the reader almost dismiss it",
    "Physical sensation precedes cognitive recognition — the body knows first",
  ],
  failureModes: [
    "The horror is introduced before the normal is established",
    "The wrongness is too obvious — there is nothing to almost-dismiss",
    "The character immediately recognizes and names the horror",
    "The uncanny element is explained before it has fully accumulated",
    "The prose style announces 'this is scary' — unheimlich requires ordinary prose",
  ],
  systemDirectives: [
    "Write the safe version first — spend real time in the normal before any deviation",
    "The first deviation must be ambiguous: a door slightly ajar, a smell that should not be there",
    "Three signals minimum before the reader should feel certain something is wrong",
    "Body sensation before cognitive recognition — 'she found she did not want to go in' before she knows why",
    "Ordinary prose throughout — the frightening sentences must not sound frightening",
    "Never use: uncanny, eerie, strange, wrong, off, disturbing as direct adjectives",
  ],
  writingNotes: "The uncanny is the hardest horror to write because it requires total trust in the reader's nervous system. The writer cannot announce the horror — they can only create the conditions for it. A wax figure that is too still. A smile that stays a beat too long. A child's drawing where the face is facing the wrong way. The specific, precise, ordinary wrong detail is everything. Vague wrongness is just vague.",
};

export const BODY_HORROR: HorrorArchetype = {
  name: "Body Horror",
  theoreticalBasis: "Carroll's art-horror requires both fear and disgust simultaneously. Body horror is the archetype where disgust dominates. Jonathan Haidt's research (2001) identifies disgust as an evolved pathogen-avoidance system that fires on specific triggers: decay, contamination, bodily violations, category mixing (things that cross the boundary between distinct categories). The crucial finding: disgust is involuntary and cannot be rationally overridden. Knowing that something is not dangerous does not eliminate the disgust response. Body horror exploits this directly — it creates scenes where the disgust fires despite any rational reassurance the reader might offer themselves.",
  coreDescription: "Body horror is about the violation of bodily integrity and the categories the body is supposed to maintain. Inside/outside. Alive/dead. Whole/fragmented. Clean/contaminated. When these categories collapse or bleed into each other, the disgust response fires involuntarily. The body is the most intimate thing we possess — its violation therefore cannot be made safe by reason.",
  baselineRequirement: "The body must be established as intact and normal before it is violated. The reader must have a baseline of the character's body as whole, functional, and correctly categorised. The horror lies in the delta.",
  onsetMechanics: "Body horror often begins with something noticed but not understood: a texture that was not there, an asymmetry that was not there, something that responds differently than it should. The character's own body becoming unfamiliar to them is more disturbing than an external threat.",
  escalationPattern: "Escalation moves from sensation to observation to recognition to implication. Something feels wrong (sensation) — the character looks (observation) — they understand what they are seeing (recognition) — they understand what it means for them (implication). The implication is the apex. What does this mean for the body's future?",
  psychologicalMechanisms: [
    "Haidt's disgust: decay, contamination, bodily violations, category mixing all trigger the pathogen-avoidance response",
    "Carroll's category violation: the thing that is simultaneously two things it cannot be",
    "Bodily autonomy horror: the body doing things the self did not instruct it to do",
    "Contamination: the clean thing that has become unclean, the spread that cannot be stopped",
    "The body-as-betrayal: the most intimate thing has become adversarial",
  ],
  readerSomaticTarget: "The involuntary physical response: the skin crawl, the urge to look away, the nausea that arrives before the conscious mind has processed the image. Haidt's research establishes this response is pre-cognitive. The goal is to produce it in text, where there is no image.",
  sacredRules: [
    "Never write 'it was disgusting' — trigger the response, do not label it",
    "Specific sensory detail produces disgust; vague description does not",
    "The wrong texture, the wrong temperature, the wrong sound — the sensory mismatch is the horror",
    "The inside/outside category violation is the most powerful: the thing that should be internal is external",
  ],
  failureModes: [
    "The body horror is described in general terms — 'there was something wrong with his skin'",
    "The disgust label is applied rather than the sensation triggered — 'it was revolting'",
    "The violation is too abstract to produce a somatic response",
    "The character's reaction overwhelms the description — tell us what they see, not what they feel about it",
    "The wrongness is resolved — body horror should leave the reader's body still responding after the scene ends",
  ],
  systemDirectives: [
    "Specific sensory modalities: texture, temperature, sound, smell — not appearance alone",
    "The inside/outside category violation: what should be internal is now visible or external",
    "The character notices the wrong detail before they understand it",
    "Write what the eyes find, not what the character feels about it",
    "The implication (what this means for the body going forward) must land after the description",
    "Never use: gross, disgusting, revolting, horrible as direct adjectives",
  ],
  writingNotes: "Body horror works best when the character's own body is the subject. The self looking at the self. The hand that does not respond correctly. The reflection that is not quite synchronised. External body horror (another person's violation) is less powerful than the body that has become a stranger to its owner. The specific wrong detail that the character cannot stop looking at is the scene's heart.",
};

export const PSYCHOLOGICAL: HorrorArchetype = {
  name: "Psychological",
  theoreticalBasis: "The threat in psychological horror may be internal. The reader and sometimes the character cannot determine whether the horror is real or produced by the character's own mind. This exploits the same epistemological uncertainty as Paranoia (in the tension library) but with a specific horror application: the possibility that the character is the source of the threat, not just the target. The research basis includes Wegner's ironic process theory (1994) — the suppressed thought intrudes — and clinical psychology of dissociation, where the self's relationship to its own actions and perceptions becomes uncertain.",
  coreDescription: "Psychological horror is about the corruption of the perceiving self. The reader cannot trust what the character is reporting. The character may not be able to trust their own perception. The horror may be real, may be hallucination, or may be the character themselves — and the story should never fully resolve which.",
  baselineRequirement: "The character must be established as reliably perceptive before their perception is corrupted. The reader needs to trust them enough to care about the corruption.",
  onsetMechanics: "The first signal of psychological horror is something the character notices and decides to dismiss. The decision to dismiss is the onset — it tells the reader the character's reliability is already uncertain. Memory becomes unreliable before perception does.",
  escalationPattern: "The reliable → unreliable journey: something the character notices → something they misremember → something they did that they cannot account for → something they did that frightens them. Each step removes a layer of certainty about the self's relationship to its own actions and perceptions.",
  psychologicalMechanisms: [
    "Wegner's ironic process theory: attempts to suppress thoughts cause their intrusion — the character cannot stop thinking the thing they are trying not to think",
    "Dissociation: the self's relationship to its own actions becomes uncertain — 'I must have done that, but I don't remember it'",
    "Epistemic horror: the corruption of the instrument of knowing — if perception is unreliable, what can be trusted?",
    "The unreliable narrator as horror device: the reader sees the gap between what the character reports and what seems true",
  ],
  readerSomaticTarget: "The reader's uncertainty about what is real. The discomfort of not knowing whether to be frightened of the external or the internal threat. The specific unease of not being able to trust the character who is the reader's guide through the story.",
  sacredRules: [
    "Never fully resolve the ambiguity — was it real? Was it the character? The story should not answer",
    "The character's self-doubt must be visible to the reader before it is visible to the character",
    "Plant the unreliable detail early — a memory that contradicts itself, a timeline that does not add up",
    "The character's attempts to reassure themselves are the best evidence that reassurance is not possible",
  ],
  failureModes: [
    "The ambiguity is resolved — the horror turns out to be clearly real or clearly internal",
    "The character is obviously unreliable from the first line — there is nothing to corrupt",
    "The reader is confused rather than uncertain — confusion is not the same as horror",
    "The character explains their own unreliability — they should not have this level of self-awareness",
  ],
  systemDirectives: [
    "Plant contradictions in the character's memory or perception early and quietly",
    "The character's reassurances to themselves should read as evidence against reassurance",
    "Something the character did and cannot account for — this is the pivot moment",
    "The reader must be at least one step ahead of the character's self-knowledge",
    "End in sustained ambiguity — was it real? The scene should not answer this",
  ],
  writingNotes: "Psychological horror is the most literary of the horror archetypes because it requires a sophisticated reader relationship. The gap between what the character knows and what the reader suspects is where the horror lives. The scene asks the reader to hold two possibilities simultaneously: the character is in danger, and the character IS the danger. Both must remain alive throughout. The moment one is eliminated, the horror collapses into either thriller or tragedy.",
};

export const COSMIC: HorrorArchetype = {
  name: "Cosmic",
  theoreticalBasis: "Lovecraft's philosophical horror: the universe is vast, indifferent, and incomprehensible. Humanity is an insignificant accident in a cosmos that does not notice us and would not care if it did. The horror comes not from a monster that wants to destroy us (that would imply we matter) but from the realisation that we do not matter at all. The threat is scale and indifference rather than malice. The human mind, confronted with genuine cosmic scale, cannot process it and breaks down — this breakdown is the horror.",
  coreDescription: "Cosmic horror is about the collapse of human significance. The character confronts something so much larger, older, or more indifferent than themselves that their framework for understanding reality ceases to function. The monster, if there is one, does not hate them. It does not notice them. That is worse.",
  baselineRequirement: "The character must be established as a person with a functioning sense of meaning, significance, and comprehensibility of the world. Cosmic horror requires dismantling a self that exists. It cannot work on a character who is already lost.",
  onsetMechanics: "Cosmic horror often begins with a wrong scale: something too large, too old, too numerous, too regular. The geometry that does not follow the rules. The pattern visible from the right distance that no single part knows it is part of. The scale that makes the body feel the size of a bacteria.",
  escalationPattern: "The scale escalation: human scale → disturbing scale → incomprehensible scale → the mind's attempt to process incomprehensible scale → the failure of that attempt. The failure is the apex. What comes after a human mind tries to contain the incomprehensible?",
  psychologicalMechanisms: [
    "Scale horror: the realisation that the human is not the measure of things and never was",
    "Indifference horror: the entity or force does not notice the character — this is more frightening than malice",
    "Comprehension failure: the mind trying to process what it cannot process, and the experience of that failure",
    "Temporal horror: the thing that has been here for geological time and will continue after humanity is gone",
    "Pattern horror: the meaningful pattern that implies a designer who did not design anything for us",
  ],
  readerSomaticTarget: "Vertigo. The specific physical sensation of one's own smallness. The disorientation that comes from scale. Not the terror of the predator but the terror of irrelevance.",
  sacredRules: [
    "The cosmic entity must not hate, notice, or pursue the character — indifference is more frightening than malice",
    "The character's mind must fail to fully process what they encounter — comprehension of the cosmic destroys it",
    "The scale must be experienced physically, not just intellectually — the body must register what the mind cannot contain",
    "The horror must be directed at human significance, not human safety",
  ],
  failureModes: [
    "The cosmic entity is just a very large monster that wants to kill the character",
    "The character understands what they are experiencing — comprehension neutralises cosmic horror",
    "The scale is described in numbers rather than felt in the body",
    "The story implies the horror can be defeated, contained, or understood",
    "The universe is angry rather than indifferent",
  ],
  systemDirectives: [
    "The entity or force must not be directed at the character — it does not know they exist",
    "The wrong scale must be felt in the body before it is processed by the mind",
    "The character's framework for understanding reality must visibly fail",
    "Temporal scale is as horrifying as spatial scale — geological time, the stars that are already dead",
    "End in the failure of comprehension, not in the comprehension of failure",
  ],
  writingNotes: "Cosmic horror is the only archetype where the monster's indifference is more terrifying than its attention. The Lovecraftian insight: we built our entire civilisation on the assumption that we matter. Cosmic horror removes that assumption. The character is not hunted — they are simply not relevant. The geometry that follows different rules. The thing that has been asleep for a million years and might stay asleep. The moment it wakes will not be because of anything we did.",
};

export const MONSTER: HorrorArchetype = {
  name: "Monster",
  theoreticalBasis: "Carroll's art-horror requires a monster — an entity that generates both fear and disgust simultaneously through category violation. The monster is monstrous because it violates our mental categories: it is simultaneously alive and dead, human and non-human, singular and multiple, familiar and alien. Carroll's paradox: we are attracted to horror monsters despite finding them repellent because our curiosity about category-violating things is engaged. The monster also functions through what Carroll calls 'impurity' — the mixing of categories that should be separate (the living dead, the animal-human).",
  coreDescription: "Monster horror is about the entity that should not exist because it violates the categories reality is supposed to maintain. The monster is not just dangerous — it is wrong. It is wrong in a way that the body registers before the mind processes. The wrongness is the horror, not the danger.",
  baselineRequirement: "The categories the monster violates must be established as categories. The reader must believe that the dead stay dead, that things are either one thing or another, before the monster can violate these expectations.",
  onsetMechanics: "The monster is almost always introduced wrongly at first — not directly but through its effects, its sounds, its absence in a place where something should be, or a partial view that allows the wrong detail to land before the full picture arrives.",
  escalationPattern: "Partial reveal → wrong detail → full reveal → implication. The partial reveal creates anticipation. The wrong detail is the first horror (what part of this is wrong?). The full reveal is Carroll's moment of art-horror. The implication is what the existence of this thing means for everything else.",
  psychologicalMechanisms: [
    "Carroll's category violation: the thing is simultaneously two things that cannot coexist",
    "Carroll's impurity: the mixing of categories that should be separate (living/dead, human/animal)",
    "Haidt's disgust: the category mixing triggers the pathogen-avoidance response involuntarily",
    "Fear + disgust fused: the monster produces both simultaneously — this is Carroll's definition of art-horror",
    "Carroll's paradox: the curiosity about rule-violating entities compels the reader to keep looking despite finding it repellent",
  ],
  readerSomaticTarget: "The fused fear+disgust response Carroll describes: the body wanting to flee and being unable to look away simultaneously. The revulsion that does not prevent looking. The specific horror of recognising a category violation before being able to name it.",
  sacredRules: [
    "The monster must violate at least one category, not just be large or dangerous",
    "Never fully reveal the monster before the partial reveal has done its work",
    "The wrong detail must land before the full picture",
    "The monster's existence must have implications beyond the immediate scene",
  ],
  failureModes: [
    "The monster is just very dangerous, not categorically wrong",
    "Full reveal without the partial reveal building to it",
    "The monster is explained — explanation reduces it to a puzzle",
    "The disgust layer is absent — the monster is only frightening, not repellent",
    "The reader understands the monster before the character does — the mystery should outlast the scene",
  ],
  systemDirectives: [
    "Introduce the monster through its effects, its sounds, or a partial view before the full reveal",
    "The wrong detail must arrive before the full picture — one part of the monster that should not be that way",
    "Both fear and disgust must be present: the monster is threatening AND wrong",
    "The category violation must be specific: it is alive+dead, or human+not-human, or singular+multiple — name which",
    "The full reveal should produce Carroll's art-horror: simultaneous fear and fascinated disgust",
    "Leave the reader's curiosity unsatisfied — the monster should retain mystery after the scene ends",
  ],
  writingNotes: "The most common mistake in monster horror is making the monster just very powerful or very dangerous. Power and danger are not horror — they are threat. The horror in monster horror comes from the wrongness, not the lethality. A monster that is merely lethal is a predator. A monster that is dead and moving, or human and not, or one thing and simultaneously its opposite — that is Carroll's art-horror. The reader cannot look away because the curiosity about the impossible category is engaged.",
};

export const COMPULSION: HorrorArchetype = {
  name: "Compulsion",
  theoreticalBasis: "Freud's Thanatos — the death drive — expressed as a compulsion that moves toward destruction against the character's conscious will. Junji Ito's Enigma of Amigara Fault: characters find holes in a cliff shaped exactly like their bodies and feel an overwhelming pull to enter, despite knowing it means death. The mechanism: the compulsion is not weakness, not insanity, not external control. The character is fully aware of what is happening and cannot stop. The horror of Amigara Fault is that the body moves toward its own destruction with the mind watching, unable to intervene. Sociogenic illness and mass psychogenic events (Dancing Plague 1518, Salem, Tanganyika laughter epidemic) show the same mechanism at scale: bodies acting against conscious will in response to a social signal. Sleep paralysis — the body immobilized while the mind watches — is the closest neurological correlate.",
  coreDescription: "The character knows exactly what is happening. They know it is wrong. They know where it leads. They move toward it anyway. The awareness does not help — it makes it worse. The horror is specifically that knowledge is insufficient to stop the compulsion. The compulsion must be retroactively inevitable: looking back, the pull was always there.",
  baselineRequirement: "The compulsion must be established as a small attractive pull before it becomes irresistible. The hole feels like it was shaped for them. The edge of the roof is interesting. The thing they should not touch is almost beautiful. Attraction before destruction — the pull must have genuine appeal before the horror begins.",
  onsetMechanics: "Three stages: (1) The thing exerts a pull that the character finds strange but not alarming. They are aware of it and can still choose. (2) The pull intensifies. The character resists and succeeds, but the resistance costs something. (3) The pull becomes irresistible. The character is moving toward the thing before they decide to. The body acts; the mind watches.",
  escalationPattern: "The escalation is the narrowing of the gap between awareness and action. Stage one: large gap (notices the pull, ignores it easily). Stage two: smaller gap (resists with effort). Stage three: gap gone (the body is already moving). The horror peaks when the character is fully conscious and fully unable to intervene.",
  psychologicalMechanisms: [
    "Freud's Thanatos: the death drive as a compulsion toward destruction",
    "Sleep paralysis structure: mind awake, body acting independently",
    "Sociogenic illness: the body responding to a signal the conscious mind cannot locate or refuse",
    "The retroactively inevitable: the pull was always there, now visible",
    "The awareness trap: knowing does not help — understanding the compulsion is not the same as being free of it",
  ],
  readerSomaticTarget: "The reader's own sense of the small compulsions they cannot explain — the edge of a high place, the intrusive thought, the thing they return to despite themselves. Recognition of the mechanism in themselves.",
  sacredRules: [
    "The character must be fully conscious throughout — the horror is specifically that consciousness is insufficient",
    "The compulsion must offer something genuinely attractive before the destruction phase",
    "The body moves before the decision — write the action before the character's awareness of deciding",
    "Freeze the horror at the moment the character realizes the gap has closed",
  ],
  failureModes: [
    "The character is unconscious or controlled externally — this removes the central horror",
    "The compulsion appears only as repulsion — the attraction must precede the destruction",
    "The character resists and succeeds permanently — the third stage never arrives",
    "The mechanism is explained before it is experienced",
  ],
  systemDirectives: [
    "Establish the attractive pull first — the compulsion offers something real before it takes",
    "Stage the narrowing: the character resists at stage two with visible effort and cost",
    "The body moves first at stage three — write the physical action before the character's mind catches up",
    "Freeze the moment the character realizes they cannot stop — do not animate what happens next",
    "The last line should be the body in motion, not the mind's reaction to the body in motion",
  ],
  writingNotes: "The Compulsion archetype works because it activates the reader's own experience of intrusive thoughts, impulses, and the small terrifying gap between knowing something is wrong and being unable to stop. The reading experience mirrors the character experience: the reader cannot stop reading about the thing they know is going to be terrible. The form enacts the content.",
};

export const SOCIAL_HORROR: HorrorArchetype = {
  name: "Social Horror",
  theoreticalBasis: "René Girard's mimetic desire: we do not desire things independently — we desire what others desire, or what we observe others fearing. In horror, the social transmission of fear is the mechanism: one person's terror becomes legible to others, who begin to feel it themselves before they know its source. Erving Goffman's social performance theory: our sense of self depends entirely on the social performance being maintained by everyone around us — when the performance begins to break down, the self becomes uncertain. Mass psychogenic illness (Salem, Dancing Plague, factory outbreaks) is the documented real-world form: bodies responding to social signals with physical symptoms, with no physical cause. The specific horror: reality is socially constructed, and when enough people stop performing it correctly, the construction fails.",
  coreDescription: "The thing that is wrong is social reality, not physical reality. The character's horror is specifically that the people around them have changed — not in their bodies but in their behavior, their shared agreement about what is real, their social performance. The horror spreads like a social contagion: one person stops performing normally, and the ones who notice begin to feel the pull themselves.",
  baselineRequirement: "Establish the social normal with precision: the specific social rituals of this group, the specific performance everyone maintains, the specific unspoken agreements that make the social world feel stable. The horror requires the reader to have inhabited the normal social world before it begins to fail.",
  onsetMechanics: "One person stops performing the social ritual correctly — not dramatically, subtly. Their eye contact is wrong. Their response to a greeting is a beat too slow. They do not laugh at the right moment. The protagonist notices and dismisses it. Then another person. Then the protagonist begins to wonder if they themselves are the one who has changed.",
  escalationPattern: "The spread: each new person who stops performing normally adds weight to the protagonist's doubt about their own perception of reality. The horror escalates from 'something is wrong with one person' to 'something is wrong with everyone' to 'something is wrong with me for thinking something is wrong' to 'something is wrong with the social world itself and I cannot locate stable ground.'",
  psychologicalMechanisms: [
    "Girard's mimetic transmission: the fear spreads because it is witnessed, not because it is reasoned",
    "Goffman's performance failure: when the social performance breaks down, identity becomes unstable",
    "Mass psychogenic illness: bodies producing symptoms in response to social signals without physical cause",
    "The protagonist's epistemic isolation: they cannot verify their own perception through social confirmation",
    "The horror of being the only one who notices — or the horror of realizing everyone else has already noticed",
  ],
  readerSomaticTarget: "The reader's own sensitivity to social wrongness — the moment in a conversation when something is off but you can't identify it. The scene that feels wrong without visible cause. The group that has subtly changed in a way that resists naming.",
  sacredRules: [
    "The wrongness must be social, not physical — no monsters, no unexplained deaths, only behavioral deviation",
    "The protagonist must doubt their own perception — the uncertainty about who has changed is essential",
    "The spread must be gradual enough that each new person's deviation could be explained away individually",
    "Freeze the moment the protagonist realizes they cannot confirm their own sanity through social validation",
  ],
  failureModes: [
    "The horror has a visible physical cause — this converts social horror to conventional horror",
    "The protagonist never doubts their own perception",
    "The social deviation is too extreme to be dismissible in its early stages",
    "The ending resolves the ambiguity — social horror should leave the constructed nature of reality uncertain",
  ],
  systemDirectives: [
    "Establish the specific social rituals and performances of this group before any deviation",
    "The first deviation must be so small that the protagonist almost convinces themselves they imagined it",
    "Increase the spread gradually — never two people deviating simultaneously at first",
    "The protagonist's isolation: they cannot verify their perception through social confirmation",
    "Do not resolve the question of who or what has changed — the uncertainty is the horror",
  ],
  writingNotes: "Social horror is most powerful in settings where social performance is already high-stakes: professional environments, family gatherings, communities with strong shared rituals. The more important the performance is to everyone present, the more horrifying its failure. The real-world anchors (Salem, Dancing Plague 1518) work because they show that these mechanisms are not fictional — they are documented features of human social psychology.",
};

export const EXISTENTIAL_HORROR: HorrorArchetype = {
  name: "Existential Horror",
  theoreticalBasis: "Terror Management Theory (Becker 1973, The Denial of Death): human culture is an elaborate defense against awareness of mortality — the mortality buffer. Religion, legacy, meaning, the sense that one's life matters: all of these are psychological structures that manage the terror of death by making it seem purposeful, distant, or transcendable. When the mortality buffer is stripped away — not death threatened, but death made meaningless, or the self made cosmically irrelevant — the result is terror that no amount of courage can address because it has no object to face. Thomas Ligotti's philosophical pessimism and Camus's Absurdism: the horror is not that you will die but that the universe is indifferent to whether you exist, and the 'meaning' you believe you inhabit was always a fiction your nervous system required.",
  coreDescription: "The horror is not the threat to the body or the self — it is the removal of the belief that the body or the self matters. Lovecraft's cosmic horror works not because the Old Gods will kill you but because in their presence, your death becomes cosmically irrelevant — smaller than irrelevant, because irrelevance requires that something relevant exists to be measured against. The existential horror archetype strips the mortality buffer without threatening the body.",
  baselineRequirement: "The character must have an active mortality buffer — a belief in their own significance, their narrative, their legacy, the meaning of their choices. The horror requires a functioning buffer to strip. A character who has already lost the sense that their life matters cannot experience existential horror — they are already past it.",
  onsetMechanics: "The stripping of the buffer: not through argument but through encounter with a scale, a perspective, a revelation that makes the character's sense of personal significance suddenly impossible to sustain. The universe does not care. Not 'does not care about them specifically' — does not care. The distinction between existing and not existing is the same magnitude as the distinction between one water molecule and another.",
  escalationPattern: "The buffer reasserts itself: the character attempts to reconstruct the sense of meaning after the initial encounter. This partial reconstruction is what makes the escalation possible — the horror returns to strip the buffer again, this time with the knowledge that reconstruction is possible and always insufficient.",
  psychologicalMechanisms: [
    "Terror Management Theory: the mortality buffer stripped rather than death threatened",
    "Cosmic insignificance: not personal mortality but the irrelevance of existence itself",
    "The return of the buffer: meaning reasserts itself and is stripped again — the cycle is the horror",
    "Ligotti's insight: consciousness itself is the source of the horror — the universe's indifference requires a conscious being to experience it",
    "The vertiginous gap between the scale of the self's experience and the scale of the universe",
  ],
  readerSomaticTarget: "The specific vertiginous feeling of genuine scale-confrontation: the 3am thought that goes too far, the moment when the stars seem wrong rather than beautiful. Not fear of death but the specific nausea of realizing that the self's sense of importance was always a construction.",
  sacredRules: [
    "The horror is the removal of meaning, not the threat to life — no monster, no death threat",
    "The mortality buffer must be present and functioning before the horror begins",
    "The scale must be real — the cosmic indifference must be genuinely incomprehensible, not merely large",
    "The character's attempt to reconstruct meaning must partially succeed before being stripped again",
  ],
  failureModes: [
    "The horror has a physical dimension — a monster, a death threat — which gives the character something to face",
    "The character has no functioning mortality buffer at the start",
    "The existential revelation is presented as an argument to be answered rather than an encounter to be survived",
    "The ending provides meaning — existential horror specifically cannot be resolved through meaning",
  ],
  systemDirectives: [
    "Establish the character's mortality buffer first — what makes their life feel significant to them?",
    "The encounter with scale must be non-arguable — not a philosophical position but a direct experiential encounter",
    "Write the specific phenomenology of the mortality buffer failing: the thoughts that cannot be thought away",
    "The partial reconstruction of meaning must be genuine — the character is not stupid, they rebuild correctly — and then the scale returns",
    "Do not provide an answer. The horror is specifically that there is no adequate answer.",
  ],
  writingNotes: "Existential horror is the hardest to write because the temptation is always to provide a consoling answer at the end — meaning reasserts itself, human connection matters, the small scale of individual experience is beautiful rather than terrifying. The archetype requires refusing that consolation. The Ligotti influence: the correct response to the universe's indifference is not to find a smaller scale where meaning lives — it is to face the fact that all scales are equally indifferent. This is not a position most writers or readers are comfortable sustaining. That discomfort is the point.",
};
