import type { CombatStyle } from "../../types";

export const HEMA_LONGSWORD: CombatStyle = {
  name: "HEMA Longsword",
  origin: "Europe (primarily Germany and Italy, 14th–17th century)",
  era: "Historical European Martial Arts; reconstructed from surviving fight manuals (Fechtbücher) of masters including Johannes Liechtenauer, Fiore dei Liberi, and Hans Talhoffer; practiced as a living art today.",
  corePhilosophy: "The HEMA longsword masters codified a sophisticated system built on a single principle: the sword is both an offensive and defensive instrument simultaneously. The Liechtenauer tradition describes this through the concept of Indes — 'instantly, in the same moment' — meaning that defense and offense are a single motion, not two sequential ones. You do not block and then strike; you strike in a way that simultaneously removes the opponent's sword from the line. The masters also describe the vier Leger (four guards) not as static positions but as philosophical stances — the fool's guard invites attack, the roof guard threatens it, the plow guards the low line, the ox guards the high line.",
  bodyMechanics: "The BNR dataset on two-handed sword mechanics establishes the mechanical principle behind the mastercuts (Meisterhäue). The Zornhau (wrath cut) is a diagonal downward cut from the shoulder that generates maximum force through full-body rotation — the BNR data shows peak blade velocity at the moment of the cut's third quarter, confirming that the cut must be allowed to extend through the target rather than arrested at contact. The Zwerchhau (thwart cut) is a horizontal cut delivered from the Ochs guard that simultaneously blocks an incoming Zornhau and strikes the opponent's head — the Indes mechanic physically embodied. The half-swording technique (gripping the blade with the off-hand to create a short, thrusting weapon) reflects the masters' recognition that a sword is a total body tool, not just a blade.",
  distancePreference: "Langes Messer (long sword measure) — the distance at which both fighters can reach each other with a full extension. Anything closer is zufechten (approaching) and anything closer than that is wrestling range (ringen).",
  footworkPrinciple: "Passing steps (Duplieren) where the entire body advances in a committed lunge-like movement, or gathering steps where the feet move together to adjust distance. The footwork is weapon-first — the feet position to optimize the cut's angle and power.",
  stances: [
    { name: "Vom Tag (From the Roof)", bodyPosition: "Sword raised overhead or at the shoulder, both hands on the hilt, body upright and slightly turned, threatening a powerful downward cut.", weightDistribution: "55% rear / 45% front", strengths: "Maximum power for the initial cut. Psychologically dominant — the raised sword demands respect.", weaknesses: "The windup is visible. An opponent who closes distance before the cut lands is inside the cut's power zone." },
    { name: "Pflug (The Plow)", bodyPosition: "Sword point forward and low, hilt beside the hip, body turned sideways to minimize target area, threatening a rising cut or thrust.", weightDistribution: "55% front / 45% rear", strengths: "The extended point threatens the opponent's approach. Rising cuts from Pflug are mechanically efficient.", weaknesses: "The low guard is open to high attacks." },
    { name: "Alber (The Fool)", bodyPosition: "Sword point to the ground, arms relaxed, body open — apparently defenseless.", weightDistribution: "50% front / 50% rear", strengths: "Invites the opponent to attack, then defeats the attack with a rising cut that passes through the attack line (Indes).", weaknesses: "Requires very fast reflexes to deploy correctly — against an opponent who recognizes it and attacks simultaneously, the window is narrow." },
  ],
  strikes: [
    { name: "Zornhau (Wrath Cut)", mechanics: "A powerful diagonal downward cut from the right shoulder to the left hip (for a right-handed fighter). The BNR data shows peak blade velocity at the cut's third quarter — the cut must not be arrested at contact but driven through. The Zornhau also serves as a mastercut: delivered against an incoming Zornhau, it simultaneously deflects the attack and strikes the opponent's head.", setup: "The opponent is at long sword measure and either attacking or open.", execution: "From Vom Tag, the body unwinds in a powerful rotation, the blade descends on a diagonal line. Against an incoming attack, the blade intercepts and continues to the head in a single motion.", recovery: "The cut ends in Pflug or a hanging guard — not fully extended.", counter: "A Zwerch (thwart cut) against the incoming Zornhau — it attacks from the opposite angle." },
    { name: "Zwerchhau (Thwart Cut)", mechanics: "A horizontal cut delivered from the Ochs guard that intercepts the opponent's blade and strikes the head simultaneously. The BNR data on perpendicular blade intercepts shows that a blade meeting another blade at 90 degrees absorbs rather than deflects — the Zwerchhau's 45-degree approach to the incoming blade redirects it while continuing to the target.", setup: "The opponent is delivering a downward cut.", execution: "From Ochs, the blade sweeps horizontally across the opponent's blade at approximately 45 degrees, redirecting it while striking the head.", recovery: "Return to Ochs or step back.", counter: "A lower Zwerch that passes under the intercepting blade's arc." },
  ],
  defenses: [
    { name: "Absetzen (Setting-Aside)", mechanics: "Rather than blocking, the practitioner steps offline and redirects the attack's point away from the body while simultaneously driving their own point toward the opponent's opening. The BNR data on angular deflection confirms that stepping offline at 45 degrees requires minimal force to redirect the incoming blade.", setup: "The opponent is thrusting.", execution: "The step is offline (45 degrees), the blade meets the incoming thrust at an angle to redirect it while the practitioner's point drives toward the opponent's exposed line.", recovery: "The thrust completes — Absetzen is a committed technique.", counter: "A circular bind that follows the redirecting blade back to the opening." },
  ],
  strengthAgainst: ["Opponents at sword measure who fight predictably — the mastercuts are specifically designed to defeat the most common attacks.", "Shorter weapon fighters who cannot reach the longsword practitioner from outside the longsword's measure.", "Unarmed opponents at any range — the sword controls every entry path."],
  weakAgainst: ["Ranged weapons — the longsword's measure is its maximum range.", "Opponents who close to wrestling distance before the first cut can be delivered.", "Multiple opponents — the longsword's power requires space for cuts that a crowded fight doesn't provide."],
  signatureTells: ["The sword is always in a meaningful guard — never held casually.", "The eyes watch the opponent's sword, not their face — the blade announces the attack.", "Footwork is deliberate and measured — the distance is always calculated.", "Before a mastercut, the guard shifts — Vom Tag loads before the Zornhau, Ochs loads before the Zwerch."],
  pacing: "HEMA longsword has a slow, deliberate approach phase followed by explosive decisive exchanges. Two experienced fighters will spend time in measure, feeling each other's pressure on the blade through the bind, before a single explosive exchange decides everything. The pacing should feel like two chess masters in the approach — then sudden, committed violence.",
  writingNotes: "A HEMA practitioner thinks in terms of lines, measures, and mastercuts — they are always aware of the blade's path and the opponent's vulnerable openings. They tend to be calm, analytical, and extremely decisive when the moment arrives.",
};
