import type { CombatStyle } from "../../types";

export const NAGINATAJUTSU: CombatStyle = {
  name: "Naginatajutsu",
  origin: "Japan",
  era: "Developed by samurai warriors from approximately the 10th century; became particularly associated with female warriors (onna-bugeisha) in the Edo period; still practiced today as naginata.",
  corePhilosophy: "The naginata is a polearm — a blade mounted on a long shaft — and its philosophy reflects its geometry. The blade is at the end of a long lever, which multiplies any movement of the hands into a large arc at the blade. This mechanical advantage means the naginata practitioner can defeat a sword opponent from a distance they cannot reach, can defeat a mounted opponent by attacking the horse's legs, and can hold multiple opponents at range. The art teaches that the polearm's distance is its primary defense: a practitioner who allows an opponent inside the polearm's range has already made a critical error.",
  bodyMechanics: "The BNR dataset on polearm mechanics establishes the key advantage of the naginata: the blade's velocity at the tip is a function of the shaft's rotation speed multiplied by the shaft's length. A slow rotation of the hands produces a fast arc at the blade. The dataset's measurement of naginata tip velocity shows that a practitioner of moderate strength can generate blade tip speeds exceeding those of a sword cut from the same body rotation — the longer lever amplifies the force. The two-handed grip provides the control needed to direct this speed: the near hand (tsurite) controls the blade's direction while the far hand (motite) drives the arc. Changing which hand is which mid-technique allows the naginata to change direction rapidly.",
  distancePreference: "Long range — the naginata's 1.8–2.4m length creates a large threat envelope.",
  footworkPrinciple: "Distance management is the primary footwork principle. The practitioner maintains the ma-ai (combat distance) at which the naginata functions and denies the opponent the ability to close. Circular footwork keeps the blade between the practitioner and the opponent.",
  stances: [
    { name: "Jodan no Kamae (Upper Guard)", bodyPosition: "Naginata raised overhead, blade angled forward and down, body turned to present the minimum profile.", weightDistribution: "55% rear / 45% front", strengths: "Blade threatens from above. Powerful downward cuts accessible immediately.", weaknesses: "The raised position exposes the practitioner to a quick closing rush before the cut can complete." },
    { name: "Chudan no Kamae (Middle Guard)", bodyPosition: "Naginata horizontal and pointing toward the opponent, blade end forward, body balanced.", weightDistribution: "50% front / 50% rear", strengths: "Direct threatening of the opponent's centerline. All major cuts and thrusts accessible.", weaknesses: "The extended blade can be batted aside by a determined attacker with a short weapon." },
  ],
  strikes: [
    { name: "Sweeping Cut (Kirioroshi)", mechanics: "A downward cutting arc that targets the opponent's shoulder, neck, or upper body. The BNR data shows the naginata's cutting arc is most powerful at the blade's lower third — the tip carries less force due to the longer lever arm's reduced control, but greater velocity. The optimal cutting zone is 30–50cm behind the tip.", setup: "The opponent is at naginata range.", execution: "From a raised guard, the blade descends in a cutting arc driven by hip rotation. The near hand guides the angle, the far hand drives the arc.", recovery: "The blade continues its arc into a lower guard rather than stopping.", counter: "Step inside the blade's optimal cutting zone — the practitioner must then reposition the naginata, which takes time." },
    { name: "Leg Sweep", mechanics: "A low horizontal sweep targeting the opponent's shins and ankles. The naginata's length allows this technique from a distance where the opponent cannot easily defend their lower line while also protecting their upper body.", setup: "The opponent is advancing, or their guard is high.", execution: "The blade drops to ankle height and sweeps in a horizontal arc across the opponent's base.", recovery: "The sweep continues into a rising guard or a retreating step.", counter: "Jump the sweep or close the distance before the arc is complete." },
  ],
  defenses: [
    { name: "Shaft Block", mechanics: "Incoming attacks are blocked with the shaft rather than the blade — the hardwood or metal-reinforced shaft is more durable than the blade for receiving impacts. The block is delivered at an angle to redirect rather than absorb.", setup: "A strike is incoming.", execution: "The shaft rises to intercept the strike at approximately 45 degrees, redirecting the force sideways.", recovery: "The block transitions immediately into a counter — the shaft's position after the block is already set for a sweeping counter.", counter: "A second strike from the other direction before the shaft can redirect." },
  ],
  strengthAgainst: ["Shorter-weapon fighters who must close through the naginata's threat envelope.", "Mounted opponents — the naginata's leg sweep was designed specifically for horse-legs.", "Multiple opponents who approach from a single direction — the long arc covers wide angles."],
  weakAgainst: ["Opponents who close distance before the naginata can be deployed.", "Confined spaces where the shaft cannot maneuver.", "Multiple opponents approaching from multiple directions simultaneously — the naginata cannot cover all angles."],
  signatureTells: ["The hands slide along the shaft constantly — adjusting the grip changes the effective arc radius.", "The feet always maintain a measured distance — the practitioner steps back automatically when the opponent advances.", "The blade is always moving slightly — circular patterns while in guard, preventing the opponent from easily reading the next attack angle."],
  pacing: "Naginatajutsu has a controlled, distant pacing that occasionally erupts into rapid cutting combinations. The practitioner moves constantly to maintain the optimal distance. When an opening appears, the response is fast and often multiple-cut. The pacing should feel like a circling — then sudden, decisive arcs.",
  writingNotes: "A naginata practitioner carries the art's spatial awareness in every context — they are always aware of their reach, the reach of everything around them, and the distance between themselves and any potential threat. They tend to be deliberate and controlled, and they are most dangerous when they are allowed to maintain their preferred distance.",
};
