export const dynamic = 'force-dynamic';

import { NextResponse } from "next/server";
import { getRequiredSession } from "@/lib/auth-helpers";
import { getUserTier, canAccessFeature } from "@/lib/subscription";
import { db } from "@/db";
import { projects, chapters, characters, locations, productionShots } from "@/db/schema";
import { eq, and, asc } from "drizzle-orm";
import { put } from "@vercel/blob";
import JSZip from "jszip";

export async function POST(
  _req: Request,
  { params }: { params: Promise<{ projectId: string }> }
) {
  const session = await getRequiredSession();
  const tier = await getUserTier(session.user.id);
  if (!canAccessFeature(tier, "export")) {
    return NextResponse.json({ error: "upgrade_required", feature: "export" }, { status: 403 });
  }

  const project = await db.query.projects.findFirst({
    where: and(eq(projects.id, (await params).projectId), eq(projects.userId, session.user.id)),
  });
  if (!project) return NextResponse.json({ error: "Not found" }, { status: 404 });

  const [allChapters, allCharacters, allLocations, allShots] = await Promise.all([
    db.query.chapters.findMany({
      where: eq(chapters.projectId, (await params).projectId),
      orderBy: [asc(chapters.sortOrder)],
    }),
    db.query.characters.findMany({ where: eq(characters.projectId, (await params).projectId) }),
    db.query.locations.findMany({ where: eq(locations.projectId, (await params).projectId) }),
    db.query.productionShots.findMany({
      where: eq(productionShots.projectId, (await params).projectId),
      orderBy: [asc(productionShots.sceneNumber), asc(productionShots.shotNumber)],
    }),
  ]);

  const zip = new JSZip();

  // 1. Episode breakdown
  const breakdown = {
    title: project.name,
    format: project.format,
    genre: (project as any).genres || [],
    totalScenes: allChapters.length,
    characters: allCharacters.map(c => ({
      name: c.name,
      role: c.role,
      soulId: c.soulId && !c.soulId.startsWith("training:") ? c.soulId : null,
      hasPortrait: !!c.portraitUrl,
    })),
    scenes: allChapters.map((ch, i) => ({
      number: i + 1,
      title: ch.title,
      synopsis: (ch.content?.slice(0, 200) ?? "") + (ch.content && ch.content.length > 200 ? "..." : ""),
    })),
  };
  zip.file("episode-breakdown.json", JSON.stringify(breakdown, null, 2));

  // 2. Character sheets
  const charFolder = zip.folder("characters")!;
  for (const c of allCharacters) {
    const sheet = {
      name: c.name, role: c.role, age: c.age,
      appearance: c.appearance, personality: c.personality,
      backstory: c.backstory, arc: c.arc,
      soulId: c.soulId && !c.soulId.startsWith("training:") ? c.soulId : null,
      portraitUrl: c.portraitUrl || null,
      voiceProfile: c.voiceProfile || null,
    };
    charFolder.file(`${c.name.replace(/\s+/g, "-").toLowerCase()}.json`, JSON.stringify(sheet, null, 2));
  }

  // 3. Locations
  zip.file("world-notes.json", JSON.stringify(
    allLocations.map(l => ({ name: l.name, description: l.description })),
    null, 2
  ));

  // 4. Production shots manifest
  if (allShots.length > 0) {
    const shotsManifest = allShots.map(s => ({
      scene: s.sceneNumber,
      shot: s.shotNumber,
      prompt: s.videoPrompt || "",
      model: (s as any).model || "kling",
      cameraPreset: s.cameraPreset || "",
      viralPreset: s.viralPreset || "",
      videoUrl: s.generatedVideoUrl || s.finalVideoUrl || null,
    }));
    zip.file("production-shots.json", JSON.stringify(shotsManifest, null, 2));
  }

  // 5. README
  const soulIdChars = allCharacters.filter(c => c.soulId && !c.soulId.startsWith("training:"));
  const readme = `# ${project.name} — Higgsfield Original Series Submission

Generated by GhostWriter AI

## Contents
- episode-breakdown.json — Full episode structure
- characters/ — Character sheets (one per character)
- world-notes.json — Locations and world details
- production-shots.json — Shot list with Higgsfield parameters and video URLs

## Characters with Soul IDs
${soulIdChars.length > 0 ? soulIdChars.map(c => `- ${c.name}: ${c.soulId}`).join("\n") : "No Soul IDs trained yet"}

## Production Status
- Scenes written: ${allChapters.filter(c => (c.content?.length ?? 0) > 100).length}/${allChapters.length}
- Characters with Soul IDs: ${soulIdChars.length}/${allCharacters.length}
- Shots generated: ${allShots.filter(s => s.generatedVideoUrl || s.finalVideoUrl).length}/${allShots.length}
`;
  zip.file("README.md", readme);

  const zipBuffer = await zip.generateAsync({ type: "nodebuffer", compression: "DEFLATE" });
  const safeTitle = project.name.replace(/[^a-z0-9]/gi, "-").toLowerCase();

  const blob = await put(
    `exports/${(await params).projectId}/higgsfield-contest-${safeTitle}.zip`,
    zipBuffer,
    { access: "public", contentType: "application/zip", addRandomSuffix: true }
  );

  return NextResponse.json({ downloadUrl: blob.url });
}
